// Region data such as classification of an area as open world area, dungeon area or near boss area 
// are from TGA table https://github.com/The-Grand-Archives/Elden-Ring-CT-TGA
pub mod regions {
    use std::{collections::HashMap, sync::Mutex};
    use once_cell::sync::Lazy;

    use crate::db::map_name::map_name::MapName;
    
    #[derive(PartialEq, Eq, Hash, Clone, Copy, PartialOrd, Ord)]
    pub enum Region {
        AbandonedCave,
        AbductorVirgin,
        AcademyCrystalCave,
        AcrosstheRoots,
        AgheelLakeNorthMurkwaterCoastGatefrontRuins,
        AinselRiverDownstream,
        AinselRiverDownstreamPartII,
        AinselRiverMain,
        AinselRiverWellDepths,
        AltusHighwayJunction,
        AltusTunnel,
        AncestralWoods,
        AqueductFacingCliffs,
        AqueductFacingCliffsPartII,
        AshenDivineBridge,
        AshenEldenThrone,
        AshenQueensBedchamber,
        AstelNaturalbornoftheVoid,
        AudiencePathway,
        AurizaHerosGrave,
        AurizaSideTomb,
        AvenueBalcony,
        BehindCariaManor,
        BellumHighway,
        BesidetheGreatBridge,
        BestialSanctum,
        BlackKnifeCatacombs,
        CaelidCatacombs,
        CaelidNorth,
        CapitalOutskirts,
        CapitalRampart,
        CariaManor,
        CastellansHall,
        CastleMorne,
        CastleSol,
        CastleSolMainGateChurchoftheEclipse,
        CastleSolRooftop,
        CathedraloftheForsaken,
        CaveofKnowledge,
        CaveoftheForlorn,
        CentralCaelid,
        CentralMountaintops,
        ChairCryptofSellia,
        ChamberOutsidethePlaza,
        ChurchofDragonCommunion,
        ChurchoftheCuckoo,
        CliffbottomCatacombs,
        CoastalCave,
        CocoonoftheEmpyrean,
        ConsecratedSnowfield,
        ConsecratedSnowfieldCatacombs,
        CrumblingBeastGrave,
        CrumblingBeastGraveDepthsTempestFacingBalcony,
        DeathtouchedCatacombs,
        DebateParlor,
        DeeprootDepths,
        DivineBridge,
        DivineTowerofCaelidBasemenr,
        DivineTowerofCaelidCenter,
        DivineTowerofEastAltus,
        DivineTowerofLimgrave,
        DivineTowerofLiurnia,
        DivineTowerofWestAltus,
        DominulaWindmillVillageRoadofIniquitySidePath,
        Dragonbarrow,
        DragonbarrowCave,
        DragonkinSoldierofNokstella,
        DragonlordPlacidusax,
        DragonTemple,
        DragonTempleAltar,
        DragonTempleLift,
        DragonTempleRooftop,
        DragonTempleTransept,
        DynastyMausoleumEntrance,
        DynastyMausoleumMidpoint,
        EarthboreCave,
        EastCapitalRampart,
        EldenBeast,
        EldenThrone,
        ElphaelInnerWallDrainageChannel,
        ErdtreeSanctuary,
        FireGiant,
        ForbiddenLands,
        ForestSpanningGreatbridge,
        ForsakenDepths,
        FracturedMarika,
        FrenziedFlameProscription,
        GaelTunnel,
        GaelTunnelPartII,
        GaolCave,
        GatesideChamber,
        GelmirHerosGrave,
        GiantConqueringHerosGrave,
        GiantsGravepostFootoftheForge,
        GiantsMountaintopCatacombs,
        GodricktheGrafted,
        GrandCloister,
        GrandCloisterPartII,
        GrandLiftofDectusJarburg,
        GrandLiftofRold,
        GreatWaterfallBasin,
        GreatWaterfallCrestPartII,
        GrovesideCave,
        GuestHall,
        HaligtreeCanopy,
        HaligtreePromenade,
        HaligtreeRoots,
        HaligtreeTownPlaza,
        HiddenPathtotheHaligtree,
        HiddenPathtotheHaligtreePartII,
        HighroadCave,
        ImpalersCatacombs,
        IsolatedDivineTower,
        KingsrealmRuins,
        LakeofRotShoreside,
        LakesideCrystalCave,
        LeyndellCapitalofAsh,
        LeyndellCatacombs,
        LeyndellCatacombsPartII,
        LiftsideChamberSecludedCell,
        LimgraveTunnels,
        LiurniaEast,
        LiurniaSouth,
        LiurniaSouthEast,
        LiurniaSouthWest,
        LiurniaWest,
        LowerCapitalChurch,
        MagmaWyrmMakar,
        MainAcademyGate,
        MainCariaManorGate,
        MaleniaGoddessofRot,
        MalikeththeBlackBlade,
        ManorLowerLevel,
        MargittheFellOmen,
        MimicTear,
        MinorErdtreeCatacombs,
        MistwoodOutskirtsFortHaightWest,
        MoonlightAltar,
        MorneMoangrave,
        MorneTunnel,
        MurkwaterCatacombs,
        MurkwaterCave,
        NightsSacredGround,
        NinthMtGelmirCampsite,
        NokronEternalCity,
        NokstellaEternalCity,
        NokstellaWaterfallBasin,
        OldAltusTunnel,
        PalaceApproachLedgeRoad,
        PerfumersGrotto,
        PrayerRoom,
        PrinceofDeathsThrone,
        PrisonTownChurch,
        QueensBedchamber,
        RampartsidePath,
        RampartTower,
        RayaLucariaCrystalTunnel,
        RayaLucariaGrandLibrary,
        RearGaelTunnelEntrance,
        RedmaneCastlePlaza,
        RoadofIniquity,
        RoadsEndCatacombs,
        RootFacingCliffs,
        RoyalMoongazingGrounds,
        RuinStrewnPrecipice,
        RuinStrewnPrecipiceOverlook,
        RykardLordofBlasphemy,
        SagesCave,
        SaintedHerosGrave,
        SchoolhouseClassroom,
        SealedTunnel,
        SeasideRuins,
        SeethewaterCave,
        SeethewaterTerminusPrimevalSorcererAzur,
        SelliaCrystalTunnel,
        SelliaHideaway,
        SiofraRiverBank,
        SiofraRiverWellDepths,
        SlumberingWolfsShack,
        SpiritcallersCave,
        StarscourgeRadahn,
        StillwaterCave,
        StormcallerChurchLuxRuins,
        StormfootCatacombs,
        Stormhill,
        StormveilMainGateStormveilCliffside,
        StrandedGraveyard,
        SubterraneanInquisitionChamber,
        SummonwaterVillageOutskirts,
        SwampofAeonia,
        TempleofEiglay,
        TheFirstStepChurchofElleh,
        TheNamelessEternalCity,
        TheRavine,
        TheShadedCastle,
        TombswardCatacombs,
        TombswardCave,
        UndergroundRoadside,
        UnsightlyCatacombs,
        VolcanoCave,
        VolcanoManor,
        WarDeadCatacombs,
        WaypointRuinsCellar,
        WeepingPeninsulaEast,
        WeepingPeninsulaWest,
        WestCapitalRampartFortifiedManorFirstFloor,
        WorshippersWoods,
        WyndhamCatacombs,
        YeloughAnixTunnel,
        ZamorRuins,
    }

    pub static ID_TO_REGION: Lazy<Mutex<HashMap<u32,Region>>> = Lazy::new(|| {
        Mutex::new(HashMap::from([
            (6100090,Region::ChurchofDragonCommunion),
            (6100000,Region::TheFirstStepChurchofElleh),
            (6100001,Region::SeasideRuins),
            (6100004,Region::MistwoodOutskirtsFortHaightWest),
            (6100002,Region::AgheelLakeNorthMurkwaterCoastGatefrontRuins),
            (6100003,Region::SummonwaterVillageOutskirts),
            (6100010,Region::WaypointRuinsCellar),
            (3002001,Region::StormfootCatacombs),
            (3004001,Region::MurkwaterCatacombs),
            (3103001,Region::GrovesideCave),
            (3115001,Region::CoastalCave),
            (3100001,Region::MurkwaterCave),
            (3117001,Region::HighroadCave),
            (3201001,Region::LimgraveTunnels),
            (1800090,Region::CaveofKnowledge),
            (1800001,Region::StrandedGraveyard),
            (6101000,Region::Stormhill),
            (6101010,Region::MargittheFellOmen),
            (3011001,Region::DeathtouchedCatacombs),
            (3410090,Region::DivineTowerofLimgrave),
            (6102001,Region::CastleMorne),
            (6102020,Region::MorneMoangrave),
            (6102000,Region::WeepingPeninsulaEast),
            (6102002,Region::WeepingPeninsulaWest),
            (3001001,Region::ImpalersCatacombs),
            (3000001,Region::TombswardCatacombs),
            (3101001,Region::EarthboreCave),
            (3102001,Region::TombswardCave),
            (3200001,Region::MorneTunnel),
            (1000001,Region::StormveilMainGateStormveilCliffside),
            (1000006,Region::GatesideChamber),
            (1000003,Region::RampartTower),
            (1000005,Region::LiftsideChamberSecludedCell),
            (1000000,Region::GodricktheGrafted),
            (6200001,Region::LiurniaSouthEast),
            (6200004,Region::LiurniaEast),
            (6200008,Region::BehindCariaManor),
            (3105090,Region::SlumberingWolfsShack),
            (6200000,Region::LiurniaSouth),
            (6200002,Region::LiurniaSouthWest),
            (6200005,Region::LiurniaWest),
            (6200003,Region::KingsrealmRuins),
            (6200007,Region::MainCariaManorGate),
            (6200007,Region::CariaManor),
            (6200007,Region::ManorLowerLevel),
            (6200010,Region::RoyalMoongazingGrounds),
            (6200006,Region::TheRavine),
            (3006001,Region::CliffbottomCatacombs),
            (3003001,Region::RoadsEndCatacombs),
            (3005001,Region::BlackKnifeCatacombs),
            (3104001,Region::StillwaterCave),
            (3105001,Region::LakesideCrystalCave),
            (3106001,Region::AcademyCrystalCave),
            (1400011,Region::MainAcademyGate),
            (3202001,Region::RayaLucariaCrystalTunnel),
            (3411090,Region::DivineTowerofLiurnia),
            (6201000,Region::BellumHighway),
            (6200090,Region::GrandLiftofDectusJarburg),
            (3920002,Region::RuinStrewnPrecipice),
            (3920003,Region::RuinStrewnPrecipiceOverlook),
            (3920000,Region::MagmaWyrmMakar),
            (6202000,Region::MoonlightAltar),
            (1400013,Region::ChurchoftheCuckoo),
            (1400015,Region::SchoolhouseClassroom),
            (1400010,Region::DebateParlor),
            (1400000,Region::RayaLucariaGrandLibrary),
            (6300005,Region::RampartsidePath),
            (6300000,Region::StormcallerChurchLuxRuins),
            (6300001,Region::TheShadedCastle),
            (6300002,Region::AltusHighwayJunction),
            (6300030,Region::CastellansHall),
            (6300003,Region::ForestSpanningGreatbridge),
            (3012001,Region::UnsightlyCatacombs),
            (3008001,Region::SaintedHerosGrave),
            (3119001,Region::SagesCave),
            (3118001,Region::PerfumersGrotto),
            (6300004,Region::DominulaWindmillVillageRoadofIniquitySidePath),
            (3204001,Region::OldAltusTunnel),
            (3205001,Region::AltusTunnel),
            (6302000,Region::NinthMtGelmirCampsite),
            (6302001,Region::RoadofIniquity),
            (6302002,Region::SeethewaterTerminusPrimevalSorcererAzur),
            (3007001,Region::WyndhamCatacombs),
            (3009001,Region::GelmirHerosGrave),
            (3107001,Region::SeethewaterCave),
            (3109001,Region::VolcanoCave),
            (6301000,Region::CapitalOutskirts),
            (6301090,Region::CapitalRampart),
            (3013091,Region::AurizaSideTomb),
            (3010001,Region::AurizaHerosGrave),
            (3412011,Region::SealedTunnel),
            (3412090,Region::DivineTowerofWestAltus),
            (1600012,Region::VolcanoManor),
            (1600014,Region::PrisonTownChurch),
            (1600010,Region::TempleofEiglay),
            (1600016,Region::GuestHall),
            (1600006,Region::AudiencePathway),
            (1600020,Region::AbductorVirgin),
            (1600022,Region::SubterraneanInquisitionChamber),
            (1600000,Region::RykardLordofBlasphemy),
            (1100010,Region::ErdtreeSanctuary),
            (1100012,Region::EastCapitalRampart),
            (1100015,Region::LowerCapitalChurch),
            (1100013,Region::AvenueBalcony),
            (1100001,Region::QueensBedchamber),
            (1100016,Region::WestCapitalRampartFortifiedManorFirstFloor),
            (1100017,Region::DivineBridge),
            (1100000,Region::EldenThrone),
            (3500002,Region::UndergroundRoadside),
            (3500008,Region::ForsakenDepths),
            (3500010,Region::LeyndellCatacombs),
            (3500011,Region::LeyndellCatacombsPartII),
            (3500092,Region::FrenziedFlameProscription),
            (3500000,Region::CathedraloftheForsaken),
            (1105011,Region::LeyndellCapitalofAsh),
            (1105001,Region::AshenQueensBedchamber),
            (1105092,Region::AshenDivineBridge),
            (1105000,Region::AshenEldenThrone),
            (1900000,Region::FracturedMarika),
            (1900001,Region::EldenBeast),
            (6400001,Region::CentralCaelid),
            (6400000,Region::CaelidNorth),
            (6400002,Region::ChamberOutsidethePlaza),
            (6400010,Region::RedmaneCastlePlaza),
            (6400040,Region::StarscourgeRadahn),
            (3014001,Region::MinorErdtreeCatacombs),
            (3015001,Region::CaelidCatacombs),
            (3016001,Region::WarDeadCatacombs),
            (3120001,Region::AbandonedCave),
            (3121001,Region::GaolCave),
            (3207001,Region::GaelTunnel),
            (3207002,Region::GaelTunnelPartII),
            (3207090,Region::RearGaelTunnelEntrance),
            (3208001,Region::SelliaCrystalTunnel),
            (6400020,Region::ChairCryptofSellia),
            (6401000,Region::SwampofAeonia),
            (6402000,Region::Dragonbarrow),
            (3111001,Region::SelliaHideaway),
            (3110001,Region::DragonbarrowCave),
            (6402001,Region::BestialSanctum),
            (3413003,Region::DivineTowerofCaelidCenter),
            (3413013,Region::DivineTowerofCaelidBasemenr),
            (3415090,Region::IsolatedDivineTower),
            (6500000,Region::ForbiddenLands),
            (6500090,Region::GrandLiftofRold),
            (3020001,Region::HiddenPathtotheHaligtree),
            (3020002,Region::HiddenPathtotheHaligtreePartII),
            (3414011,Region::DivineTowerofEastAltus),
            (6501000,Region::ZamorRuins),
            (6501001,Region::CentralMountaintops),
            (6501002,Region::CastleSol),
            (3122001,Region::SpiritcallersCave),
            (6501003,Region::CastleSolMainGateChurchoftheEclipse),
            (6501010,Region::CastleSolRooftop),
            (6502000,Region::GiantsGravepostFootoftheForge),
            (6502010,Region::FireGiant),
            (3018001,Region::GiantsMountaintopCatacombs),
            (3017002,Region::GiantConqueringHerosGrave),
            (6503000,Region::ConsecratedSnowfield),
            (3019001,Region::ConsecratedSnowfieldCatacombs),
            (3112001,Region::CaveoftheForlorn),
            (3211001,Region::YeloughAnixTunnel),
            (1500011,Region::HaligtreeCanopy),
            (1500012,Region::HaligtreeTownPlaza),
            (1500010,Region::HaligtreePromenade),
            (1500001,Region::PrayerRoom),
            (1500002,Region::ElphaelInnerWallDrainageChannel),
            (1500003,Region::HaligtreeRoots),
            (1500000,Region::MaleniaGoddessofRot),
            (1201001,Region::AinselRiverWellDepths),
            (1201002,Region::AinselRiverDownstream),
            (1201003,Region::AinselRiverDownstreamPartII),
            (1204000,Region::AstelNaturalbornoftheVoid),
            (1201000,Region::DragonkinSoldierofNokstella),
            (1201011,Region::AinselRiverMain),
            (1201013,Region::NokstellaEternalCity),
            (1201014,Region::NokstellaWaterfallBasin),
            (1201015,Region::LakeofRotShoreside),
            (1201016,Region::GrandCloister),
            (1201017,Region::GrandCloisterPartII),
            (1207026,Region::NokronEternalCity),
            (1202020,Region::MimicTear),
            (1202002,Region::AncestralWoods),
            (1202007,Region::NightsSacredGround),
            (1202003,Region::AqueductFacingCliffs),
            (1202004,Region::AqueductFacingCliffsPartII),
            (1202000,Region::GreatWaterfallBasin),
            (1205001,Region::PalaceApproachLedgeRoad),
            (1205004,Region::DynastyMausoleumEntrance),
            (1205006,Region::DynastyMausoleumMidpoint),
            (1205000,Region::CocoonoftheEmpyrean),
            (1207031,Region::SiofraRiverWellDepths),
            (1202033,Region::SiofraRiverBank),
            (1202034,Region::WorshippersWoods),
            (1203001,Region::RootFacingCliffs),
            (1203002,Region::GreatWaterfallCrestPartII),
            (1203003,Region::DeeprootDepths),
            (1203004,Region::TheNamelessEternalCity),
            (1203005,Region::AcrosstheRoots),
            (1203000,Region::PrinceofDeathsThrone),
            (1300012,Region::CrumblingBeastGrave),
            (1300013,Region::CrumblingBeastGraveDepthsTempestFacingBalcony),
            (1300017,Region::DragonTemple),
            (1300018,Region::DragonTempleTransept),
            (1300010,Region::DragonTempleAltar),
            (1300019,Region::DragonTempleLift),
            (1300003,Region::DragonTempleRooftop),
            (1300020,Region::DragonlordPlacidusax),
            (1300006,Region::BesidetheGreatBridge),
            (1300000,Region::MalikeththeBlackBlade),
        ]))
    });

    
    //key, id, name, map, is_open_world, is_dungeon, is_boss
    pub static REGIONS: Lazy<Mutex<HashMap<Region, (u32, &str, MapName, bool, bool, bool)>>> = Lazy::new(|| {
        Mutex::new(HashMap::from([
            (Region::ChurchofDragonCommunion, (6100090,"Church of Dragon Communion", MapName::Limgrave, true, false, false)),
            (Region::TheFirstStepChurchofElleh, (6100000,"The First Step, Church of Elleh", MapName::Limgrave, true, false, false)),
            (Region::SeasideRuins, (6100001,"Seaside Ruins", MapName::Limgrave, true, false, false)),
            (Region::MistwoodOutskirtsFortHaightWest, (6100004,"Mistwood Outskirts, Fort Haight West", MapName::Limgrave, true, false, false)),
            (Region::AgheelLakeNorthMurkwaterCoastGatefrontRuins, (6100002,"Agheel Lake North, Murkwater Coast, Gatefront Ruins", MapName::Limgrave, true, false, false)),
            (Region::SummonwaterVillageOutskirts, (6100003,"Summonwater Village Outskirts", MapName::Limgrave, true, false, false)),
            (Region::WaypointRuinsCellar, (6100010,"Waypoint Ruins Cellar", MapName::Limgrave, true, false, false)),
            (Region::StormfootCatacombs, (3002001,"Stormfoot Catacombs", MapName::Limgrave, false, true, false)),
            (Region::MurkwaterCatacombs, (3004001,"Murkwater Catacombs", MapName::Limgrave, false, true, false)),
            (Region::GrovesideCave, (3103001,"Groveside Cave", MapName::Limgrave, false, true, false)),
            (Region::CoastalCave, (3115001,"Coastal Cave", MapName::Limgrave, false, true, false)),
            (Region::MurkwaterCave, (3100001,"Murkwater Cave", MapName::Limgrave, false, true, false)),
            (Region::HighroadCave, (3117001,"Highroad Cave", MapName::Limgrave, false, true, false)),
            (Region::LimgraveTunnels, (3201001,"Limgrave Tunnels", MapName::Limgrave, false, true, false)),
            
            (Region::CaveofKnowledge, (1800090,"Cave of Knowledge", MapName::StrandedGraveyard, false, true, false)),
            (Region::StrandedGraveyard, (1800001,"Stranded Graveyard", MapName::StrandedGraveyard, false, true, false)),
            
            (Region::Stormhill, (6101000,"Stormhill", MapName::Stormhill, true, false, false)),
            (Region::MargittheFellOmen, (6101010,"Margit, the Fell Omen", MapName::Stormhill, false, false, true)),
            (Region::DeathtouchedCatacombs, (3011001,"Deathtouched Catacombs", MapName::Stormhill, false, true, false)),
            (Region::DivineTowerofLimgrave, (3410090,"Divine Tower of Limgrave", MapName::Stormhill, false, false, false)),

            (Region::CastleMorne, (6102001,"Castle Morne", MapName::WeepingPeninsula, false, false, true)),
            (Region::MorneMoangrave, (6102020,"Morne Moangrave", MapName::WeepingPeninsula, false, false, true)),
            (Region::WeepingPeninsulaEast, (6102000,"Weeping Peninsula East", MapName::WeepingPeninsula, true, false, false)),
            (Region::WeepingPeninsulaWest, (6102002,"Weeping Peninsula West", MapName::WeepingPeninsula, true, false, false)),
            (Region::ImpalersCatacombs, (3001001,"Impaler's Catacombs", MapName::WeepingPeninsula, false, true, false)),
            (Region::TombswardCatacombs, (3000001,"Tombsward Catacombs", MapName::WeepingPeninsula, false, true, false)),
            (Region::EarthboreCave, (3101001,"Earthbore Cave", MapName::WeepingPeninsula, false, true, false)),
            (Region::TombswardCave, (3102001,"Tombsward Cave", MapName::WeepingPeninsula, false, true, false)),
            (Region::MorneTunnel, (3200001,"Morne Tunnel", MapName::WeepingPeninsula, false, true, false)),

            (Region::StormveilMainGateStormveilCliffside, (1000001,"Stormveil Main Gate, Stormveil Cliffside", MapName::StormveilCastle, false, false, false)),
            (Region::GatesideChamber, (1000006,"Gateside Chamber", MapName::StormveilCastle, false, false, false)),
            (Region::RampartTower, (1000003,"Rampart Tower", MapName::StormveilCastle, false, false, false)),
            (Region::LiftsideChamberSecludedCell, (1000005,"Liftside Chamber, Secluded Cell", MapName::StormveilCastle, false, false, true)),
            (Region::GodricktheGrafted, (1000000,"Godrick the Grafted", MapName::StormveilCastle, false, false, true)),

            (Region::LiurniaSouthEast, (6200001,"Liurnia South-East", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::LiurniaEast, (6200004,"Liurnia East", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::BehindCariaManor, (6200008,"Behind Caria Manor", MapName::LiurniaOfTheLakes, false, false, false)),
            (Region::SlumberingWolfsShack, (3105090,"Slumbering Wolf's Shack", MapName::LiurniaOfTheLakes, false, false, false)),
            (Region::LiurniaSouth, (6200000,"Liurnia South", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::LiurniaSouthWest, (6200002,"Liurnia South-West", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::LiurniaWest, (6200005,"Liurnia West", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::KingsrealmRuins, (6200003,"Kingsrealm Ruins", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::MainCariaManorGate, (6200007,"Main Caria Manor Gate", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::CariaManor, (6200007,"Caria Manor", MapName::LiurniaOfTheLakes, false, false, false)),
            (Region::ManorLowerLevel, (6200007,"Manor Lower Level", MapName::LiurniaOfTheLakes, false, false, false)),
            (Region::RoyalMoongazingGrounds, (6200010,"Royal Moongazing Grounds", MapName::LiurniaOfTheLakes, false, false, false)),
            (Region::TheRavine, (6200006,"The Ravine", MapName::LiurniaOfTheLakes, true, false, false)),
            (Region::CliffbottomCatacombs, (3006001,"Cliffbottom Catacombs", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::RoadsEndCatacombs, (3003001,"Road's End Catacombs", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::BlackKnifeCatacombs, (3005001,"Black Knife Catacombs", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::StillwaterCave, (3104001,"Stillwater Cave", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::LakesideCrystalCave, (3105001,"Lakeside Crystal Cave", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::AcademyCrystalCave, (3106001,"Academy Crystal Cave", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::MainAcademyGate, (1400011,"Main Academy Gate", MapName::LiurniaOfTheLakes, false, false, false)),
            (Region::RayaLucariaCrystalTunnel, (3202001,"Raya Lucaria Crystal Tunnel", MapName::LiurniaOfTheLakes, false, true, false)),
            (Region::DivineTowerofLiurnia, (3411090,"Divine Tower of Liurnia", MapName::LiurniaOfTheLakes, false, false, false)),


            (Region::BellumHighway, (6201000,"Bellum Highway", MapName::BellumHighway, true, false, false)),
            (Region::GrandLiftofDectusJarburg, (6200090,"Grand Lift of Dectus, Jarburg", MapName::BellumHighway, true, false, false)),

            (Region::RuinStrewnPrecipice, (3920002,"Ruin-Strewn Precipice", MapName::RuinStrewnPrecipice, false, false, false)),
            (Region::RuinStrewnPrecipiceOverlook, (3920003,"Ruin-Strewn Precipice Overlook", MapName::RuinStrewnPrecipice, false, false, true)),
            (Region::MagmaWyrmMakar, (3920000,"Magma Wyrm Makar", MapName::RuinStrewnPrecipice, false, false, true)),

            (Region::MoonlightAltar, (6202000,"Moonlight Altar", MapName::MoonlightAltar, false, false, false)),

            (Region::ChurchoftheCuckoo, (1400013,"Church of the Cuckoo", MapName::AcademyOfRayaLucaria, false, false, false)),
            (Region::SchoolhouseClassroom, (1400015,"Schoolhouse Classroom", MapName::AcademyOfRayaLucaria, false, false, false)),
            (Region::DebateParlor, (1400010,"Debate Parlor", MapName::AcademyOfRayaLucaria, false, false, false)),
            (Region::RayaLucariaGrandLibrary, (1400000,"Raya Lucaria Grand Library", MapName::AcademyOfRayaLucaria, false, false, true)),

            (Region::RampartsidePath, (6300005,"Rampartside Path", MapName::AltusPlateau, true, false, false)),
            (Region::StormcallerChurchLuxRuins, (6300000,"Stormcaller Church, Lux Ruins", MapName::AltusPlateau, true, false, false)),
            (Region::TheShadedCastle, (6300001,"The Shaded Castle", MapName::AltusPlateau, false, false, false)),
            (Region::AltusHighwayJunction, (6300002,"Altus Highway Junction", MapName::AltusPlateau, true, false, false)),
            (Region::CastellansHall, (6300030,"Castellan's Hall", MapName::AltusPlateau, false, false, false)),
            (Region::ForestSpanningGreatbridge, (6300003,"Forest-Spanning Greatbridge", MapName::AltusPlateau, true, false, false)),
            (Region::UnsightlyCatacombs, (3012001,"Unsightly Catacombs", MapName::AltusPlateau, false, true, false)),
            (Region::SaintedHerosGrave, (3008001,"Sainted Hero's Grave", MapName::AltusPlateau, false, true, false)),
            (Region::SagesCave, (3119001,"Sage's Cave", MapName::AltusPlateau, false, true, false)),
            (Region::PerfumersGrotto, (3118001,"Perfumer's Grotto", MapName::AltusPlateau, false, true, false)),
            (Region::DominulaWindmillVillageRoadofIniquitySidePath, (6300004,"Dominula, Windmill Village, Road of Iniquity Side Path", MapName::AltusPlateau, true, false, false)),
            (Region::OldAltusTunnel, (3204001,"Old Altus Tunnel", MapName::AltusPlateau, false, true, false)),
            (Region::AltusTunnel, (3205001,"Altus Tunnel", MapName::AltusPlateau, false, true, false)),

            (Region::NinthMtGelmirCampsite, (6302000,"Ninth Mt. Gelmir Campsite", MapName::MtGelmir, true, false, false)),
            (Region::RoadofIniquity, (6302001,"Road of Iniquity", MapName::MtGelmir, true, false, false)),
            (Region::SeethewaterTerminusPrimevalSorcererAzur, (6302002,"Seethewater Terminus, Primeval Sorcerer Azur", MapName::MtGelmir, true, false, false)),
            (Region::WyndhamCatacombs, (3007001,"Wyndham Catacombs", MapName::MtGelmir, false, true, false)),
            (Region::GelmirHerosGrave, (3009001,"Gelmir Hero's Grave", MapName::MtGelmir, false, true, false)),
            (Region::SeethewaterCave, (3107001,"Seethewater Cave", MapName::MtGelmir, false, true, false)),
            (Region::VolcanoCave, (3109001,"Volcano Cave", MapName::MtGelmir, false, true, false)),

            (Region::CapitalOutskirts, (6301000,"Capital Outskirts", MapName::CapitalOutskirts, true, false, false)),
            (Region::CapitalRampart, (6301090,"Capital Rampart", MapName::CapitalOutskirts, true, false, false)),
            (Region::AurizaSideTomb, (3013091,"Auriza Side Tomb", MapName::CapitalOutskirts, false, true, false)),
            (Region::AurizaHerosGrave, (3010001,"Auriza Hero's Grave", MapName::CapitalOutskirts, false, true, false)),
            (Region::SealedTunnel, (3412011,"Sealed Tunnel", MapName::CapitalOutskirts, false, true, false)),
            (Region::DivineTowerofWestAltus, (3412090,"Divine Tower of West Altus", MapName::CapitalOutskirts, false, false, false)),

            (Region::VolcanoManor, (1600012,"Volcano Manor", MapName::VolcanoManor, false, false, false)),
            (Region::PrisonTownChurch, (1600014,"Prison Town Church", MapName::VolcanoManor, false, false, false)),
            (Region::TempleofEiglay, (1600010,"Temple of Eiglay", MapName::VolcanoManor, false, false, false)),
            (Region::GuestHall, (1600016,"Guest Hall", MapName::VolcanoManor, false, false, false)),
            (Region::AudiencePathway, (1600006,"Audience Pathway", MapName::VolcanoManor, false, false, true)),
            (Region::AbductorVirgin, (1600020,"Abductor Virgin", MapName::VolcanoManor, false, true, false)),
            (Region::SubterraneanInquisitionChamber, (1600022,"Subterranean Inquisition Chamber", MapName::VolcanoManor, false, false, false)),
            (Region::RykardLordofBlasphemy, (1600000,"Rykard, Lord of Blasphemy", MapName::VolcanoManor, false, false, true)),
            
            (Region::ErdtreeSanctuary, (1100010,"Erdtree Sanctuary", MapName::LeyndellRoyalCapital, false, false, false)),
            (Region::EastCapitalRampart, (1100012,"East Capital Rampart", MapName::LeyndellRoyalCapital, false, false, false)),
            (Region::LowerCapitalChurch, (1100015,"Lower Capital Church", MapName::LeyndellRoyalCapital, false, false, false)),
            (Region::AvenueBalcony, (1100013,"Avenue Balcony", MapName::LeyndellRoyalCapital, false, false, false)),
            (Region::QueensBedchamber, (1100001,"Queen's Bedchamber", MapName::LeyndellRoyalCapital, false, false, true)),
            (Region::WestCapitalRampartFortifiedManorFirstFloor, (1100016,"West Capital Rampart, Fortified Manor, First Floor", MapName::LeyndellRoyalCapital, false, false, false)),
            (Region::DivineBridge, (1100017,"Divine Bridge", MapName::LeyndellRoyalCapital, false, false, false)),
            (Region::EldenThrone, (1100000,"Elden Throne", MapName::LeyndellRoyalCapital, false, false, true)),

            (Region::UndergroundRoadside, (3500002,"Underground Roadside", MapName::SubterraneanShunningGrounds, false, false, false)),
            (Region::ForsakenDepths, (3500008,"Forsaken Depths", MapName::SubterraneanShunningGrounds, false, false, true)),
            (Region::LeyndellCatacombs, (3500010,"Leyndell Catacombs", MapName::SubterraneanShunningGrounds, false, false, false)),
            (Region::LeyndellCatacombsPartII, (3500011,"Leyndell Catacombs Part II", MapName::SubterraneanShunningGrounds, false, false, false)),
            (Region::FrenziedFlameProscription, (3500092,"Frenzied Flame Proscription", MapName::SubterraneanShunningGrounds, false, false, false)),
            (Region::CathedraloftheForsaken, (3500000,"Cathedral of the Forsaken", MapName::SubterraneanShunningGrounds, false, false, false)),

            (Region::LeyndellCapitalofAsh, (1105011,"Leyndell, Capital of Ash", MapName::LeyndellAshenCapital, false, false, true)),
            (Region::AshenQueensBedchamber, (1105001,"Queen's Bedchamber ", MapName::LeyndellAshenCapital, false, false, true)),
            (Region::AshenDivineBridge, (1105092,"Divine Bridge ", MapName::LeyndellAshenCapital, false, false, false)),
            (Region::AshenEldenThrone, (1105000,"Elden Throne ", MapName::LeyndellAshenCapital, false, false, true)),

            (Region::FracturedMarika, (1900000,"Fractured Marika", MapName::StonePlatform, false, false, true)),
            (Region::EldenBeast, (1900001,"Elden Beast", MapName::StonePlatform, false, false, true)),

            (Region::CentralCaelid, (6400001,"Central Caelid", MapName::Caelid, true, false, false)),
            (Region::CaelidNorth, (6400000,"Caelid North", MapName::Caelid, true, false, false)),
            (Region::ChamberOutsidethePlaza, (6400002,"Chamber Outside the Plaza", MapName::Caelid, false, false, true)),
            (Region::RedmaneCastlePlaza, (6400010,"Redmane Castle Plaza", MapName::Caelid, false, false, false)),
            (Region::StarscourgeRadahn, (6400040,"Starscourge Radahn", MapName::Caelid, false, false, true)),
            (Region::MinorErdtreeCatacombs, (3014001,"Minor Erdtree Catacombs", MapName::Caelid, false, true, false)),
            (Region::CaelidCatacombs, (3015001,"Caelid Catacombs", MapName::Caelid, false, true, false)),
            (Region::WarDeadCatacombs, (3016001,"War-Dead Catacombs", MapName::Caelid, false, true, false)),
            (Region::AbandonedCave, (3120001,"Abandoned Cave", MapName::Caelid, false, true, false)),
            (Region::GaolCave, (3121001,"Gaol Cave", MapName::Caelid, false, true, false)),
            (Region::GaelTunnel, (3207001,"Gael Tunnel", MapName::Caelid, false, true, false)),
            (Region::GaelTunnelPartII, (3207002,"Gael Tunnel Part II", MapName::Caelid, false, true, false)),
            (Region::RearGaelTunnelEntrance, (3207090,"Rear Gael Tunnel Entrance", MapName::Caelid, false, true, false)),
            (Region::SelliaCrystalTunnel, (3208001,"Sellia Crystal Tunnel", MapName::Caelid, false, true, false)),
            (Region::ChairCryptofSellia, (6400020,"Chair-Crypt of Sellia", MapName::Caelid, true, false, false)),

            (Region::SwampofAeonia, (6401000,"Swamp of Aeonia", MapName::SwampOfAeonia, true, false, false)),

            (Region::Dragonbarrow, (6402000,"Dragonbarrow", MapName::GreyollsDragonbarrow, true, false, false)),
            (Region::SelliaHideaway, (3111001,"Sellia Hideaway", MapName::GreyollsDragonbarrow, true, false, false)),
            (Region::DragonbarrowCave, (3110001,"Dragonbarrow Cave", MapName::GreyollsDragonbarrow, true, false, false)),
            (Region::BestialSanctum, (6402001,"Bestial Sanctum", MapName::GreyollsDragonbarrow, true, false, false)),
            (Region::DivineTowerofCaelidCenter, (3413003,"Divine Tower of Caelid: Center", MapName::GreyollsDragonbarrow, false, false, false)),
            (Region::DivineTowerofCaelidBasemenr, (3413013,"Divine Tower of Caelid: Basement", MapName::GreyollsDragonbarrow, false, false, true)),
            (Region::IsolatedDivineTower, (3415090,"Isolated Divine Tower", MapName::GreyollsDragonbarrow, false, false, false)),

            (Region::ForbiddenLands, (6500000,"Forbidden Lands", MapName::ForbiddenLands, true, false, false)),
            (Region::GrandLiftofRold, (6500090,"Grand Lift of Rold", MapName::ForbiddenLands, true, false, false)),
            (Region::HiddenPathtotheHaligtree, (3020001,"Hidden Path to the Haligtree", MapName::ForbiddenLands, false, true, false)),
            (Region::HiddenPathtotheHaligtreePartII, (3020002,"Hidden Path to the Haligtree Part II", MapName::ForbiddenLands, false, true, false)),
            (Region::DivineTowerofEastAltus, (3414011,"Divine Tower of East Altus", MapName::ForbiddenLands, false, false, false)),

            (Region::ZamorRuins, (6501000,"Zamor Ruins", MapName::MountaintopsOfTheGiants, true, false, false)),
            (Region::CentralMountaintops, (6501001,"Central Mountaintops", MapName::MountaintopsOfTheGiants, true, false, false)),
            (Region::CastleSol, (6501002,"Castle Sol", MapName::MountaintopsOfTheGiants, true, false, false)),
            (Region::SpiritcallersCave, (3122001,"Spiritcaller's Cave", MapName::MountaintopsOfTheGiants, false, true, false)),
            (Region::CastleSolMainGateChurchoftheEclipse, (6501003,"Castle Sol Main Gate, Church of the Eclipse", MapName::MountaintopsOfTheGiants, true, false, false)),
            (Region::CastleSolRooftop, (6501010,"Castle Sol Rooftop", MapName::MountaintopsOfTheGiants, true, false, false)),

            (Region::GiantsGravepostFootoftheForge, (6502000,"Giants' Gravepost, Foot of the Forge", MapName::FlamePeak, false, false, true)),
            (Region::FireGiant, (6502010,"Fire Giant", MapName::FlamePeak, false, false, true)),
            (Region::GiantsMountaintopCatacombs, (3018001,"Giants' Mountaintop Catacombs", MapName::FlamePeak, false, true, false)),
            (Region::GiantConqueringHerosGrave, (3017002,"Giant-Conquering Hero's Grave", MapName::FlamePeak, false, true, false)),

            (Region::ConsecratedSnowfield, (6503000,"Consecrated Snowfield", MapName::ConsecratedSnowfield, true, false, false)),
            (Region::ConsecratedSnowfieldCatacombs, (3019001,"Consecrated Snowfield Catacombs", MapName::ConsecratedSnowfield, false, true, false)),
            (Region::CaveoftheForlorn, (3112001,"Cave of the Forlorn", MapName::ConsecratedSnowfield, false, true, false)),
            (Region::YeloughAnixTunnel, (3211001,"Yelough Anix Tunnel", MapName::ConsecratedSnowfield, false, true, false)),

            (Region::HaligtreeCanopy, (1500011,"Haligtree Canopy", MapName::MiquellasHaligtree, false, false, false)),
            (Region::HaligtreeTownPlaza, (1500012,"Haligtree Town Plaza", MapName::MiquellasHaligtree, false, false, true)),
            (Region::HaligtreePromenade, (1500010,"Haligtree Promenade", MapName::MiquellasHaligtree, false, false, true)),

            (Region::PrayerRoom, (1500001,"Prayer Room", MapName::ElphaelBraceOfTheHaligtree, false, false, false)),
            (Region::ElphaelInnerWallDrainageChannel, (1500002,"Elphael Inner Wall, Drainage Channel", MapName::ElphaelBraceOfTheHaligtree, false, false, false)),
            (Region::HaligtreeRoots, (1500003,"Haligtree Roots", MapName::ElphaelBraceOfTheHaligtree, false, false, true)),
            (Region::MaleniaGoddessofRot, (1500000,"Malenia, Goddess of Rot", MapName::ElphaelBraceOfTheHaligtree, false, false, true)),

            (Region::AinselRiverWellDepths, (1201001,"Ainsel River Well Depths", MapName::AinselRiver, false, false, false)),
            (Region::AinselRiverDownstream, (1201002,"Ainsel River Downstream", MapName::AinselRiver, false, false, false)),
            (Region::AinselRiverDownstreamPartII, (1201003,"Ainsel River Downstream Part II", MapName::AinselRiver, false, false, false)),
            (Region::AstelNaturalbornoftheVoid, (1204000,"Astel, Naturalborn of the Void", MapName::AinselRiver, false, false, true)),
            (Region::DragonkinSoldierofNokstella, (1201000,"Dragonkin Soldier of Nokstella", MapName::AinselRiver, false, false, false)),

            (Region::AinselRiverMain, (1201011,"Ainsel River Main", MapName::AinselRiverMain, false, false, false)),
            (Region::NokstellaEternalCity, (1201013,"Nokstella, Eternal City", MapName::AinselRiverMain, false, false, false)),
            (Region::NokstellaWaterfallBasin, (1201014,"Nokstella Waterfall Basin", MapName::AinselRiverMain, false, false, false)),

            (Region::LakeofRotShoreside, (1201015,"Lake of Rot Shoreside", MapName::LakeOfRot, false, false, false)),
            (Region::GrandCloister, (1201016,"Grand Cloister", MapName::LakeOfRot, false, false, false)),
            (Region::GrandCloisterPartII, (1201017,"Grand Cloister Part II", MapName::LakeOfRot, false, false, false)),

            (Region::NokronEternalCity, (1207026,"Nokron, Eternal City", MapName::NokronEternalCity, false, false, false)),
            (Region::MimicTear, (1202020,"Mimic Tear", MapName::NokronEternalCity, false, false, false)),
            (Region::AncestralWoods, (1202002,"Ancestral Woods", MapName::NokronEternalCity, false, false, false)),
            (Region::NightsSacredGround, (1202007,"Night's Sacred Ground", MapName::NokronEternalCity, false, false, false)),
            (Region::AqueductFacingCliffs, (1202003,"Aqueduct-Facing Cliffs", MapName::NokronEternalCity, false, false, false)),
            (Region::AqueductFacingCliffsPartII, (1202004,"Aqueduct-Facing Cliffs Part II", MapName::NokronEternalCity, false, false, true)),
            (Region::GreatWaterfallBasin, (1202000,"Great Waterfall Basin", MapName::NokronEternalCity, false, false, true)),

            (Region::PalaceApproachLedgeRoad, (1205001,"Palace Approach Ledge-Road", MapName::MohgwynPalace, false, false, false)),
            (Region::DynastyMausoleumEntrance, (1205004,"Dynasty Mausoleum Entrance", MapName::MohgwynPalace, false, false, false)),
            (Region::DynastyMausoleumMidpoint, (1205006,"Dynasty Mausoleum Midpoint", MapName::MohgwynPalace, false, false, true)),
            (Region::CocoonoftheEmpyrean, (1205000,"Cocoon of the Empyrean", MapName::MohgwynPalace, false, false, true)),

            (Region::SiofraRiverWellDepths, (1207031,"Siofra River Well Depths", MapName::SiofraRiver, false, false, false)),
            (Region::SiofraRiverBank, (1202033,"Siofra River Bank", MapName::SiofraRiver, false, false, false)),
            (Region::WorshippersWoods, (1202034,"Worshippers' Woods", MapName::SiofraRiver, false, false, false)),

            (Region::RootFacingCliffs, (1203001,"Root-Facing Cliffs", MapName::DeeprootDepths, false, false, false)),
            (Region::GreatWaterfallCrestPartII, (1203002,"Great Waterfall Crest Part II", MapName::DeeprootDepths, false, false, false)),
            (Region::DeeprootDepths, (1203003,"Deeproot Depths", MapName::DeeprootDepths, false, false, false)),
            (Region::TheNamelessEternalCity, (1203004,"The Nameless Eternal City", MapName::DeeprootDepths, false, false, false)),
            (Region::AcrosstheRoots, (1203005,"Across the Roots", MapName::DeeprootDepths, false, false, true)),
            (Region::PrinceofDeathsThrone, (1203000,"Prince of Death's Throne", MapName::DeeprootDepths, false, false, true)),

            (Region::CrumblingBeastGrave, (1300012,"Crumbling Beast Grave", MapName::CrumblingFarumAzula, false, false, false)),
            (Region::CrumblingBeastGraveDepthsTempestFacingBalcony, (1300013,"Crumbling Beast Grave Depths, Tempest-Facing Balcony", MapName::CrumblingFarumAzula, false, false, false)),
            (Region::DragonTemple, (1300017,"Dragon Temple", MapName::CrumblingFarumAzula, false, false, true)),
            (Region::DragonTempleTransept, (1300018,"Dragon Temple Transept", MapName::CrumblingFarumAzula, false, false, true)),
            (Region::DragonTempleAltar, (1300010,"Dragon Temple Altar", MapName::CrumblingFarumAzula, false, false, true)),
            (Region::DragonTempleLift, (1300019,"Dragon Temple Lift", MapName::CrumblingFarumAzula, false, false, false)),
            (Region::DragonTempleRooftop, (1300003,"Dragon Temple Rooftop", MapName::CrumblingFarumAzula, false, false, false)),
            (Region::DragonlordPlacidusax, (1300020,"Dragonlord Placidusax", MapName::CrumblingFarumAzula, false, false, true)),
            (Region::BesidetheGreatBridge, (1300006,"Beside the Great Bridge", MapName::CrumblingFarumAzula, false, false, true)),
            (Region::MalikeththeBlackBlade, (1300000,"Maliketh, the Black Blade", MapName::CrumblingFarumAzula, false, false, true)),
        ]))
    });
}