// Region data such as classification of an area as open world area, dungeon area or near boss area
// are from TGA table https://github.com/The-Grand-Archives/Elden-Ring-CT-TGA
use std::{collections::HashMap, sync::OnceLock};

use crate::db::map_name::MapName;

#[derive(PartialEq, Eq, Hash, Clone, Copy, PartialOrd, Ord)]
pub enum Region {
    AbandonedCave,
    AbductorVirgin,
    AcademyCrystalCave,
    AcrosstheRoots,
    AgheelLakeNorthMurkwaterCoastGatefrontRuins,
    AinselRiverDownstream,
    AinselRiverDownstreamPartII,
    AinselRiverMain,
    AinselRiverWellDepths,
    AltusHighwayJunction,
    AltusTunnel,
    AncestralWoods,
    AqueductFacingCliffs,
    AqueductFacingCliffsPartII,
    AshenDivineBridge,
    AshenEldenThrone,
    AshenQueensBedchamber,
    AstelNaturalbornoftheVoid,
    AudiencePathway,
    AurizaHerosGrave,
    AurizaSideTomb,
    AvenueBalcony,
    BehindCariaManor,
    BellumHighway,
    BesidetheGreatBridge,
    BestialSanctum,
    BlackKnifeCatacombs,
    CaelidCatacombs,
    CaelidNorth,
    CapitalOutskirts,
    CapitalRampart,
    CariaManor,
    CastellansHall,
    CastleMorne,
    CastleSol,
    CastleSolMainGateChurchoftheEclipse,
    CastleSolRooftop,
    CathedraloftheForsaken,
    CaveofKnowledge,
    CaveoftheForlorn,
    CentralCaelid,
    CentralMountaintops,
    ChairCryptofSellia,
    ChamberOutsidethePlaza,
    ChurchofDragonCommunion,
    ChurchoftheCuckoo,
    CliffbottomCatacombs,
    CoastalCave,
    CocoonoftheEmpyrean,
    ConsecratedSnowfield,
    ConsecratedSnowfieldCatacombs,
    CrumblingBeastGrave,
    CrumblingBeastGraveDepthsTempestFacingBalcony,
    DeathtouchedCatacombs,
    DebateParlor,
    DeeprootDepths,
    DivineBridge,
    DivineTowerofCaelidBasemenr,
    DivineTowerofCaelidCenter,
    DivineTowerofEastAltus,
    DivineTowerofLimgrave,
    DivineTowerofLiurnia,
    DivineTowerofWestAltus,
    DominulaWindmillVillageRoadofIniquitySidePath,
    Dragonbarrow,
    DragonbarrowCave,
    DragonkinSoldierofNokstella,
    DragonlordPlacidusax,
    DragonTemple,
    DragonTempleAltar,
    DragonTempleLift,
    DragonTempleRooftop,
    DragonTempleTransept,
    DynastyMausoleumEntrance,
    DynastyMausoleumMidpoint,
    EarthboreCave,
    EastCapitalRampart,
    EldenBeast,
    EldenThrone,
    ElphaelInnerWallDrainageChannel,
    ErdtreeSanctuary,
    FireGiant,
    ForbiddenLands,
    ForestSpanningGreatbridge,
    ForsakenDepths,
    FracturedMarika,
    FrenziedFlameProscription,
    GaelTunnel,
    GaelTunnelPartII,
    GaolCave,
    GatesideChamber,
    GelmirHerosGrave,
    GiantConqueringHerosGrave,
    GiantsGravepostFootoftheForge,
    GiantsMountaintopCatacombs,
    GodricktheGrafted,
    GrandCloister,
    GrandCloisterPartII,
    GrandLiftofDectusJarburg,
    GrandLiftofRold,
    GreatWaterfallBasin,
    GreatWaterfallCrestPartII,
    GrovesideCave,
    GuestHall,
    HaligtreeCanopy,
    HaligtreePromenade,
    HaligtreeRoots,
    HaligtreeTownPlaza,
    HiddenPathtotheHaligtree,
    HiddenPathtotheHaligtreePartII,
    HighroadCave,
    ImpalersCatacombs,
    IsolatedDivineTower,
    KingsrealmRuins,
    LakeofRotShoreside,
    LakesideCrystalCave,
    LeyndellCapitalofAsh,
    LeyndellCatacombs,
    LeyndellCatacombsPartII,
    LiftsideChamberSecludedCell,
    LimgraveTunnels,
    LiurniaEast,
    LiurniaSouth,
    LiurniaSouthEast,
    LiurniaSouthWest,
    LiurniaWest,
    LowerCapitalChurch,
    MagmaWyrmMakar,
    MainAcademyGate,
    MainCariaManorGate,
    MaleniaGoddessofRot,
    MalikeththeBlackBlade,
    ManorLowerLevel,
    MargittheFellOmen,
    MimicTear,
    MinorErdtreeCatacombs,
    MistwoodOutskirtsFortHaightWest,
    MoonlightAltar,
    MorneMoangrave,
    MorneTunnel,
    MurkwaterCatacombs,
    MurkwaterCave,
    NightsSacredGround,
    NinthMtGelmirCampsite,
    NokronEternalCity,
    NokstellaEternalCity,
    NokstellaWaterfallBasin,
    OldAltusTunnel,
    PalaceApproachLedgeRoad,
    PerfumersGrotto,
    PrayerRoom,
    PrinceofDeathsThrone,
    PrisonTownChurch,
    QueensBedchamber,
    RampartsidePath,
    RampartTower,
    RayaLucariaCrystalTunnel,
    RayaLucariaGrandLibrary,
    RearGaelTunnelEntrance,
    RedmaneCastlePlaza,
    RoadofIniquity,
    RoadsEndCatacombs,
    RootFacingCliffs,
    RoyalMoongazingGrounds,
    RuinStrewnPrecipice,
    RuinStrewnPrecipiceOverlook,
    RykardLordofBlasphemy,
    SagesCave,
    SaintedHerosGrave,
    SchoolhouseClassroom,
    SealedTunnel,
    SeasideRuins,
    SeethewaterCave,
    SeethewaterTerminusPrimevalSorcererAzur,
    SelliaCrystalTunnel,
    SelliaHideaway,
    SiofraRiverBank,
    SiofraRiverWellDepths,
    SlumberingWolfsShack,
    SpiritcallersCave,
    StarscourgeRadahn,
    StillwaterCave,
    StormcallerChurchLuxRuins,
    StormfootCatacombs,
    Stormhill,
    StormveilMainGateStormveilCliffside,
    StrandedGraveyard,
    SubterraneanInquisitionChamber,
    SummonwaterVillageOutskirts,
    SwampofAeonia,
    TempleofEiglay,
    TheFirstStepChurchofElleh,
    TheNamelessEternalCity,
    TheRavine,
    TheShadedCastle,
    TombswardCatacombs,
    TombswardCave,
    UndergroundRoadside,
    UnsightlyCatacombs,
    VolcanoCave,
    VolcanoManor,
    WarDeadCatacombs,
    WaypointRuinsCellar,
    WeepingPeninsulaEast,
    WeepingPeninsulaWest,
    WestCapitalRampartFortifiedManorFirstFloor,
    WorshippersWoods,
    WyndhamCatacombs,
    YeloughAnixTunnel,
    ZamorRuins,
    NonInvadeableRegion,

    // DLC
    BeluratTheatreoftheDivineBeast,
    BeluratBeluratTowerSettlement,
    BeluratStagefront,
    EnirIlimGateofDivinity,
    EnirIlimOuterWall,
    EnirIlimSpiralRise,
    EnirIlimCleansingChamberAnteroom,
    EnirIlimDivineGateFrontStaircase,
    ShadowKeepMainGate,
    ShadowKeepMainGatePlaza,
    ShadowKeepChurchDistrictEntrance,
    ShadowKeepSunkenChapel,
    ShadowKeepTreeWorshipSanctum,
    StorehouseMessmersDarkChamber,
    StorehouseFirstFloor,
    StorehouseFourthFloor,
    StorehouseSeventhFloor,
    StorehouseDarkChamberEntrance,
    StorehouseBackSection,
    StorehouseLoft,
    StorehouseWestRampart,
    StoneCoffinFissureGardenofDeepPurple,
    StoneCoffinFissureStoneCoffinFissure,
    StoneCoffinFissureFissureCross,
    StoneCoffinFissureFissureWaypointDepths,
    MidrasManseDiscussionChamber,
    MidrasManseManseHall,
    MidrasManseMidrasLibrary,
    GravesitePlainFogRiftCatacombs,
    GravesitePlainRuinedForgeLavaIntake,
    GravesitePlainRivermouthCave,
    GravesitePlainDragonsPit,
    GravesitePlainDragonsPitTerminus,
    GravesitePlainGravesitePlain,
    GravesitePlainEllacRiverCave,
    GravesitePlainPillarPath,
    GravesitePlainBeluratGaol,
    GravesitePlainEllacRiverDownstream,
    CharosHiddenGraveCharosHiddenGrave,
    CharosHiddenGraveLamentersGaol,
    CastleEnsisCastleEnsis,
    CastleEnsisEnsisMoongazingGrounds,
    CeruleanCoastCeruleanCoast,
    CeruleanCoastTheFissure,
    AbyssalWoodsAbyssalWoods,
    AbyssalWoodsForsakenGraveyard,
    FootoftheJaggedPeak,
    JaggedPeakMountainside,
    JaggedPeakSummit,
    JaggedPeakRestoftheDreadDragon,
    AncientRuinsofRauhWest,
    AncientRuinsofRauhChurchoftheBud,
    AncientRuinsofRauhEast,
    RauhBaseAncientRuins,
    RauhBaseScorpionRiverCatacombs,
    RauhBaseTaylewsRuinedForge,
    ScaduAltusFingerBirthingGrounds,
    ScaduAltusScaduAltus,
    ScaduAltusBonnyVillage,
    ScaduAltusCastleWateringHole,
    ScaduAltusReclusesRiverDownstream,
    ScaduAltusDarklightCatacombs,
    ScaduAltusBonnyGaol,
    ScaduAltusRuinedForgeofStarfallPast,
    ScaduviewScadutreeBase,
    ScaduviewScaduview,
    ScaduviewShadowKeepBackGate,
    ScaduviewHinterland,
}

impl From<u32> for Region {
    #[rustfmt::skip]
    fn from(region_id: u32) -> Self {
        match region_id {
            region_id if region_id == 6100090 => Region::ChurchofDragonCommunion,
            region_id if region_id == 6100000 => Region::TheFirstStepChurchofElleh,
            region_id if region_id == 6100001 => Region::SeasideRuins,
            region_id if region_id == 6100004 => Region::MistwoodOutskirtsFortHaightWest,
            region_id if region_id == 6100002 => Region::AgheelLakeNorthMurkwaterCoastGatefrontRuins,
            region_id if region_id == 6100003 => Region::SummonwaterVillageOutskirts,
            region_id if region_id == 6100010 => Region::WaypointRuinsCellar,
            region_id if region_id == 3002001 => Region::StormfootCatacombs,
            region_id if region_id == 3004001 => Region::MurkwaterCatacombs,
            region_id if region_id == 3103001 => Region::GrovesideCave,
            region_id if region_id == 3115001 => Region::CoastalCave,
            region_id if region_id == 3100001 => Region::MurkwaterCave,
            region_id if region_id == 3117001 => Region::HighroadCave,
            region_id if region_id == 3201001 => Region::LimgraveTunnels,
            region_id if region_id == 1800090 => Region::CaveofKnowledge,
            region_id if region_id == 1800001 => Region::StrandedGraveyard,
            region_id if region_id == 6101000 => Region::Stormhill,
            region_id if region_id == 6101010 => Region::MargittheFellOmen,
            region_id if region_id == 3011001 => Region::DeathtouchedCatacombs,
            region_id if region_id == 3410090 => Region::DivineTowerofLimgrave,
            region_id if region_id == 6102001 => Region::CastleMorne,
            region_id if region_id == 6102020 => Region::MorneMoangrave,
            region_id if region_id == 6102000 => Region::WeepingPeninsulaEast,
            region_id if region_id == 6102002 => Region::WeepingPeninsulaWest,
            region_id if region_id == 3001001 => Region::ImpalersCatacombs,
            region_id if region_id == 3000001 => Region::TombswardCatacombs,
            region_id if region_id == 3101001 => Region::EarthboreCave,
            region_id if region_id == 3102001 => Region::TombswardCave,
            region_id if region_id == 3200001 => Region::MorneTunnel,
            region_id if region_id == 1000001 => Region::StormveilMainGateStormveilCliffside,
            region_id if region_id == 1000006 => Region::GatesideChamber,
            region_id if region_id == 1000003 => Region::RampartTower,
            region_id if region_id == 1000005 => Region::LiftsideChamberSecludedCell,
            region_id if region_id == 1000000 => Region::GodricktheGrafted,
            region_id if region_id == 6200001 => Region::LiurniaSouthEast,
            region_id if region_id == 6200004 => Region::LiurniaEast,
            region_id if region_id == 6200008 => Region::BehindCariaManor,
            region_id if region_id == 3105090 => Region::SlumberingWolfsShack,
            region_id if region_id == 6200000 => Region::LiurniaSouth,
            region_id if region_id == 6200002 => Region::LiurniaSouthWest,
            region_id if region_id == 6200005 => Region::LiurniaWest,
            region_id if region_id == 6200003 => Region::KingsrealmRuins,
            // TODO: Fix these duplictaes
            region_id if region_id == 6200007 => Region::MainCariaManorGate,
            region_id if region_id == 6200007 => Region::CariaManor,
            region_id if region_id == 6200007 => Region::ManorLowerLevel,
            region_id if region_id == 6200010 => Region::RoyalMoongazingGrounds,
            region_id if region_id == 6200006 => Region::TheRavine,
            region_id if region_id == 3006001 => Region::CliffbottomCatacombs,
            region_id if region_id == 3003001 => Region::RoadsEndCatacombs,
            region_id if region_id == 3005001 => Region::BlackKnifeCatacombs,
            region_id if region_id == 3104001 => Region::StillwaterCave,
            region_id if region_id == 3105001 => Region::LakesideCrystalCave,
            region_id if region_id == 3106001 => Region::AcademyCrystalCave,
            region_id if region_id == 1400011 => Region::MainAcademyGate,
            region_id if region_id == 3202001 => Region::RayaLucariaCrystalTunnel,
            region_id if region_id == 3411090 => Region::DivineTowerofLiurnia,
            region_id if region_id == 6201000 => Region::BellumHighway,
            region_id if region_id == 6200090 => Region::GrandLiftofDectusJarburg,
            region_id if region_id == 3920002 => Region::RuinStrewnPrecipice,
            region_id if region_id == 3920003 => Region::RuinStrewnPrecipiceOverlook,
            region_id if region_id == 3920000 => Region::MagmaWyrmMakar,
            region_id if region_id == 6202000 => Region::MoonlightAltar,
            region_id if region_id == 1400013 => Region::ChurchoftheCuckoo,
            region_id if region_id == 1400015 => Region::SchoolhouseClassroom,
            region_id if region_id == 1400010 => Region::DebateParlor,
            region_id if region_id == 1400000 => Region::RayaLucariaGrandLibrary,
            region_id if region_id == 6300005 => Region::RampartsidePath,
            region_id if region_id == 6300000 => Region::StormcallerChurchLuxRuins,
            region_id if region_id == 6300001 => Region::TheShadedCastle,
            region_id if region_id == 6300002 => Region::AltusHighwayJunction,
            region_id if region_id == 6300030 => Region::CastellansHall,
            region_id if region_id == 6300003 => Region::ForestSpanningGreatbridge,
            region_id if region_id == 3012001 => Region::UnsightlyCatacombs,
            region_id if region_id == 3008001 => Region::SaintedHerosGrave,
            region_id if region_id == 3119001 => Region::SagesCave,
            region_id if region_id == 3118001 => Region::PerfumersGrotto,
            region_id if region_id == 6300004 => Region::DominulaWindmillVillageRoadofIniquitySidePath,
            region_id if region_id == 3204001 => Region::OldAltusTunnel,
            region_id if region_id == 3205001 => Region::AltusTunnel,
            region_id if region_id == 6302000 => Region::NinthMtGelmirCampsite,
            region_id if region_id == 6302001 => Region::RoadofIniquity,
            region_id if region_id == 6302002 => Region::SeethewaterTerminusPrimevalSorcererAzur,
            region_id if region_id == 3007001 => Region::WyndhamCatacombs,
            region_id if region_id == 3009001 => Region::GelmirHerosGrave,
            region_id if region_id == 3107001 => Region::SeethewaterCave,
            region_id if region_id == 3109001 => Region::VolcanoCave,
            region_id if region_id == 6301000 => Region::CapitalOutskirts,
            region_id if region_id == 6301090 => Region::CapitalRampart,
            region_id if region_id == 3013091 => Region::AurizaSideTomb,
            region_id if region_id == 3010001 => Region::AurizaHerosGrave,
            region_id if region_id == 3412011 => Region::SealedTunnel,
            region_id if region_id == 3412090 => Region::DivineTowerofWestAltus,
            region_id if region_id == 1600012 => Region::VolcanoManor,
            region_id if region_id == 1600014 => Region::PrisonTownChurch,
            region_id if region_id == 1600010 => Region::TempleofEiglay,
            region_id if region_id == 1600016 => Region::GuestHall,
            region_id if region_id == 1600006 => Region::AudiencePathway,
            region_id if region_id == 1600020 => Region::AbductorVirgin,
            region_id if region_id == 1600022 => Region::SubterraneanInquisitionChamber,
            region_id if region_id == 1600000 => Region::RykardLordofBlasphemy,
            region_id if region_id == 1100010 => Region::ErdtreeSanctuary,
            region_id if region_id == 1100012 => Region::EastCapitalRampart,
            region_id if region_id == 1100015 => Region::LowerCapitalChurch,
            region_id if region_id == 1100013 => Region::AvenueBalcony,
            region_id if region_id == 1100001 => Region::QueensBedchamber,
            region_id if region_id == 1100016 => Region::WestCapitalRampartFortifiedManorFirstFloor,
            region_id if region_id == 1100017 => Region::DivineBridge,
            region_id if region_id == 1100000 => Region::EldenThrone,
            region_id if region_id == 3500002 => Region::UndergroundRoadside,
            region_id if region_id == 3500008 => Region::ForsakenDepths,
            region_id if region_id == 3500010 => Region::LeyndellCatacombs,
            region_id if region_id == 3500011 => Region::LeyndellCatacombsPartII,
            region_id if region_id == 3500092 => Region::FrenziedFlameProscription,
            region_id if region_id == 3500000 => Region::CathedraloftheForsaken,
            region_id if region_id == 1105011 => Region::LeyndellCapitalofAsh,
            region_id if region_id == 1105001 => Region::AshenQueensBedchamber,
            region_id if region_id == 1105092 => Region::AshenDivineBridge,
            region_id if region_id == 1105000 => Region::AshenEldenThrone,
            region_id if region_id == 1900000 => Region::FracturedMarika,
            region_id if region_id == 1900001 => Region::EldenBeast,
            region_id if region_id == 6400001 => Region::CentralCaelid,
            region_id if region_id == 6400000 => Region::CaelidNorth,
            region_id if region_id == 6400002 => Region::ChamberOutsidethePlaza,
            region_id if region_id == 6400010 => Region::RedmaneCastlePlaza,
            region_id if region_id == 6400040 => Region::StarscourgeRadahn,
            region_id if region_id == 3014001 => Region::MinorErdtreeCatacombs,
            region_id if region_id == 3015001 => Region::CaelidCatacombs,
            region_id if region_id == 3016001 => Region::WarDeadCatacombs,
            region_id if region_id == 3120001 => Region::AbandonedCave,
            region_id if region_id == 3121001 => Region::GaolCave,
            region_id if region_id == 3207001 => Region::GaelTunnel,
            region_id if region_id == 3207002 => Region::GaelTunnelPartII,
            region_id if region_id == 3207090 => Region::RearGaelTunnelEntrance,
            region_id if region_id == 3208001 => Region::SelliaCrystalTunnel,
            region_id if region_id == 6400020 => Region::ChairCryptofSellia,
            region_id if region_id == 6401000 => Region::SwampofAeonia,
            region_id if region_id == 6402000 => Region::Dragonbarrow,
            region_id if region_id == 3111001 => Region::SelliaHideaway,
            region_id if region_id == 3110001 => Region::DragonbarrowCave,
            region_id if region_id == 6402001 => Region::BestialSanctum,
            region_id if region_id == 3413003 => Region::DivineTowerofCaelidCenter,
            region_id if region_id == 3413013 => Region::DivineTowerofCaelidBasemenr,
            region_id if region_id == 3415090 => Region::IsolatedDivineTower,
            region_id if region_id == 6500000 => Region::ForbiddenLands,
            region_id if region_id == 6500090 => Region::GrandLiftofRold,
            region_id if region_id == 3020001 => Region::HiddenPathtotheHaligtree,
            region_id if region_id == 3020002 => Region::HiddenPathtotheHaligtreePartII,
            region_id if region_id == 3414011 => Region::DivineTowerofEastAltus,
            region_id if region_id == 6501000 => Region::ZamorRuins,
            region_id if region_id == 6501001 => Region::CentralMountaintops,
            region_id if region_id == 6501002 => Region::CastleSol,
            region_id if region_id == 3122001 => Region::SpiritcallersCave,
            region_id if region_id == 6501003 => Region::CastleSolMainGateChurchoftheEclipse,
            region_id if region_id == 6501010 => Region::CastleSolRooftop,
            region_id if region_id == 6502000 => Region::GiantsGravepostFootoftheForge,
            region_id if region_id == 6502010 => Region::FireGiant,
            region_id if region_id == 3018001 => Region::GiantsMountaintopCatacombs,
            region_id if region_id == 3017002 => Region::GiantConqueringHerosGrave,
            region_id if region_id == 6503000 => Region::ConsecratedSnowfield,
            region_id if region_id == 3019001 => Region::ConsecratedSnowfieldCatacombs,
            region_id if region_id == 3112001 => Region::CaveoftheForlorn,
            region_id if region_id == 3211001 => Region::YeloughAnixTunnel,
            region_id if region_id == 1500011 => Region::HaligtreeCanopy,
            region_id if region_id == 1500012 => Region::HaligtreeTownPlaza,
            region_id if region_id == 1500010 => Region::HaligtreePromenade,
            region_id if region_id == 1500001 => Region::PrayerRoom,
            region_id if region_id == 1500002 => Region::ElphaelInnerWallDrainageChannel,
            region_id if region_id == 1500003 => Region::HaligtreeRoots,
            region_id if region_id == 1500000 => Region::MaleniaGoddessofRot,
            region_id if region_id == 1201001 => Region::AinselRiverWellDepths,
            region_id if region_id == 1201002 => Region::AinselRiverDownstream,
            region_id if region_id == 1201003 => Region::AinselRiverDownstreamPartII,
            region_id if region_id == 1204000 => Region::AstelNaturalbornoftheVoid,
            region_id if region_id == 1201000 => Region::DragonkinSoldierofNokstella,
            region_id if region_id == 1201011 => Region::AinselRiverMain,
            region_id if region_id == 1201013 => Region::NokstellaEternalCity,
            region_id if region_id == 1201014 => Region::NokstellaWaterfallBasin,
            region_id if region_id == 1201015 => Region::LakeofRotShoreside,
            region_id if region_id == 1201016 => Region::GrandCloister,
            region_id if region_id == 1201017 => Region::GrandCloisterPartII,
            region_id if region_id == 1207026 => Region::NokronEternalCity,
            region_id if region_id == 1202020 => Region::MimicTear,
            region_id if region_id == 1202002 => Region::AncestralWoods,
            region_id if region_id == 1202007 => Region::NightsSacredGround,
            region_id if region_id == 1202003 => Region::AqueductFacingCliffs,
            region_id if region_id == 1202004 => Region::AqueductFacingCliffsPartII,
            region_id if region_id == 1202000 => Region::GreatWaterfallBasin,
            region_id if region_id == 1205001 => Region::PalaceApproachLedgeRoad,
            region_id if region_id == 1205004 => Region::DynastyMausoleumEntrance,
            region_id if region_id == 1205006 => Region::DynastyMausoleumMidpoint,
            region_id if region_id == 1205000 => Region::CocoonoftheEmpyrean,
            region_id if region_id == 1207031 => Region::SiofraRiverWellDepths,
            region_id if region_id == 1202033 => Region::SiofraRiverBank,
            region_id if region_id == 1202034 => Region::WorshippersWoods,
            region_id if region_id == 1203001 => Region::RootFacingCliffs,
            region_id if region_id == 1203002 => Region::GreatWaterfallCrestPartII,
            region_id if region_id == 1203003 => Region::DeeprootDepths,
            region_id if region_id == 1203004 => Region::TheNamelessEternalCity,
            region_id if region_id == 1203005 => Region::AcrosstheRoots,
            region_id if region_id == 1203000 => Region::PrinceofDeathsThrone,
            region_id if region_id == 1300012 => Region::CrumblingBeastGrave,
            region_id if region_id == 1300013 => Region::CrumblingBeastGraveDepthsTempestFacingBalcony,
            region_id if region_id == 1300017 => Region::DragonTemple,
            region_id if region_id == 1300018 => Region::DragonTempleTransept,
            region_id if region_id == 1300010 => Region::DragonTempleAltar,
            region_id if region_id == 1300019 => Region::DragonTempleLift,
            region_id if region_id == 1300003 => Region::DragonTempleRooftop,
            region_id if region_id == 1300020 => Region::DragonlordPlacidusax,
            region_id if region_id == 1300006 => Region::BesidetheGreatBridge,
            region_id if region_id == 1300000 => Region::MalikeththeBlackBlade,

            // DLC
            region_id if region_id == 2000000 => Region::BeluratTheatreoftheDivineBeast,
            region_id if region_id == 2000001 => Region::BeluratBeluratTowerSettlement,
            region_id if region_id == 2000002 => Region::BeluratStagefront,
            region_id if region_id == 2001000 => Region::EnirIlimGateofDivinity,
            region_id if region_id == 2001001 => Region::EnirIlimOuterWall,
            region_id if region_id == 2001004 => Region::EnirIlimSpiralRise,
            region_id if region_id == 2001005 => Region::EnirIlimCleansingChamberAnteroom,
            region_id if region_id == 2001007 => Region::EnirIlimDivineGateFrontStaircase,
            region_id if region_id == 6900000 => Region::ShadowKeepMainGate,
            region_id if region_id == 6900010 => Region::ShadowKeepMainGatePlaza,
            region_id if region_id == 2100011 => Region::ShadowKeepChurchDistrictEntrance,
            region_id if region_id == 2100014 => Region::ShadowKeepSunkenChapel,
            region_id if region_id == 2100015 => Region::ShadowKeepTreeWorshipSanctum,
            region_id if region_id == 2101000 => Region::StorehouseMessmersDarkChamber,
            region_id if region_id == 2101001 => Region::StorehouseFirstFloor,
            region_id if region_id == 2101003 => Region::StorehouseFourthFloor,
            region_id if region_id == 2101004 => Region::StorehouseSeventhFloor,
            region_id if region_id == 2101006 => Region::StorehouseDarkChamberEntrance,
            region_id if region_id == 2101011 => Region::StorehouseBackSection,
            region_id if region_id == 2101012 => Region::StorehouseLoft,
            region_id if region_id == 2102001 => Region::StorehouseWestRampart,
            region_id if region_id == 2200000 => Region::StoneCoffinFissureGardenofDeepPurple,
            region_id if region_id == 2200001 => Region::StoneCoffinFissureStoneCoffinFissure,
            region_id if region_id == 2200002 => Region::StoneCoffinFissureFissureCross,
            region_id if region_id == 2200004 => Region::StoneCoffinFissureFissureWaypointDepths,
            region_id if region_id == 6860010 => Region::MidrasManseDiscussionChamber,
            region_id if region_id == 6860001 => Region::MidrasManseManseHall,
            region_id if region_id == 6860004 => Region::MidrasManseMidrasLibrary,
            region_id if region_id == 4000001 => Region::GravesitePlainFogRiftCatacombs,
            region_id if region_id == 4200090 => Region::GravesitePlainRuinedForgeLavaIntake,
            region_id if region_id == 4300001 => Region::GravesitePlainRivermouthCave,
            region_id if region_id == 4200090 => Region::GravesitePlainDragonsPit,
            region_id if region_id == 4301090 => Region::GravesitePlainDragonsPitTerminus,
            region_id if region_id == 6800000 => Region::GravesitePlainGravesitePlain,
            region_id if region_id == 6810001 => Region::GravesitePlainEllacRiverCave,
            region_id if region_id == 6810000 => Region::GravesitePlainPillarPath,
            region_id if region_id == 4100001 => Region::GravesitePlainBeluratGaol,
            region_id if region_id == 6810090 => Region::GravesitePlainEllacRiverDownstream,
            region_id if region_id == 6840000 => Region::CharosHiddenGraveCharosHiddenGrave,
            region_id if region_id == 4102001 => Region::CharosHiddenGraveLamentersGaol,
            region_id if region_id == 6820000 => Region::CastleEnsisCastleEnsis,
            region_id if region_id == 6820010 => Region::CastleEnsisEnsisMoongazingGrounds,
            region_id if region_id == 6830000 => Region::CeruleanCoastCeruleanCoast,
            region_id if region_id == 6830002 => Region::CeruleanCoastTheFissure,
            region_id if region_id == 6860000 => Region::AbyssalWoodsAbyssalWoods,
            region_id if region_id == 4002000 => Region::AbyssalWoodsForsakenGraveyard,
            region_id if region_id == 6841000 => Region::FootoftheJaggedPeak,
            region_id if region_id == 6850000 => Region::JaggedPeakMountainside,
            region_id if region_id == 6850001 => Region::JaggedPeakSummit,
            region_id if region_id == 6850010 => Region::JaggedPeakRestoftheDreadDragon,
            region_id if region_id == 6941000 => Region::AncientRuinsofRauhWest,
            region_id if region_id == 6941010 => Region::AncientRuinsofRauhChurchoftheBud,
            region_id if region_id == 6940000 => Region::AncientRuinsofRauhEast,
            region_id if region_id == 6901000 => Region::RauhBaseAncientRuins,
            region_id if region_id == 4001001 => Region::RauhBaseScorpionRiverCatacombs,
            region_id if region_id == 4203090 => Region::RauhBaseTaylewsRuinedForge,
            region_id if region_id == 2500000 => Region::ScaduAltusFingerBirthingGrounds,
            region_id if region_id == 6900000 => Region::ScaduAltusScaduAltus,
            region_id if region_id == 6902000 => Region::ScaduAltusBonnyVillage,
            region_id if region_id == 6903090 => Region::ScaduAltusCastleWateringHole,
            region_id if region_id == 6903000 => Region::ScaduAltusReclusesRiverDownstream,
            region_id if region_id == 4002001 => Region::ScaduAltusDarklightCatacombs,
            region_id if region_id == 4101001 => Region::ScaduAltusBonnyGaol,
            region_id if region_id == 4202090 => Region::ScaduAltusRuinedForgeofStarfallPast,
            region_id if region_id == 2100010 => Region::ScaduviewScadutreeBase,
            region_id if region_id == 2101010 => Region::ScaduviewScaduview,
            region_id if region_id == 2101013 => Region::ScaduviewShadowKeepBackGate,
            region_id if region_id == 6930000 => Region::ScaduviewHinterland,
            
            _ => Region::NonInvadeableRegion
        }
    }
}

impl Region {
    //key, id, name, map, is_open_world, is_dungeon, is_boss
    #[rustfmt::skip]
    pub fn regions() -> &'static HashMap<Region, (u32, &'static str, MapName, bool, bool, bool)> {
        static REGIONS: OnceLock<HashMap<Region, (u32, &'static str, MapName, bool, bool, bool)>> = OnceLock::new();

        REGIONS.get_or_init(||
            HashMap::from([
                ( Region::ChurchofDragonCommunion, ( 6100090, "Church of Dragon Communion", MapName::Limgrave, true, false, false, ), ),
                ( Region::TheFirstStepChurchofElleh, ( 6100000, "The First Step, Church of Elleh", MapName::Limgrave, true, false, false, ), ),
                ( Region::SeasideRuins, ( 6100001, "Seaside Ruins", MapName::Limgrave, true, false, false, ), ),
                ( Region::MistwoodOutskirtsFortHaightWest, ( 6100004, "Mistwood Outskirts, Fort Haight West", MapName::Limgrave, true, false, false, ), ),
                ( Region::AgheelLakeNorthMurkwaterCoastGatefrontRuins, ( 6100002, "Agheel Lake North, Murkwater Coast, Gatefront Ruins", MapName::Limgrave, true, false, false, ), ),
                ( Region::SummonwaterVillageOutskirts, ( 6100003, "Summonwater Village Outskirts", MapName::Limgrave, true, false, false, ), ),
                ( Region::WaypointRuinsCellar, ( 6100010, "Waypoint Ruins Cellar", MapName::Limgrave, true, false, false, ), ),
                ( Region::StormfootCatacombs, ( 3002001, "Stormfoot Catacombs", MapName::Limgrave, false, true, false, ), ),
                ( Region::MurkwaterCatacombs, ( 3004001, "Murkwater Catacombs", MapName::Limgrave, false, true, false, ), ),
                ( Region::GrovesideCave, ( 3103001, "Groveside Cave", MapName::Limgrave, false, true, false, ), ),
                ( Region::CoastalCave, ( 3115001, "Coastal Cave", MapName::Limgrave, false, true, false, ), ),
                ( Region::MurkwaterCave, ( 3100001, "Murkwater Cave", MapName::Limgrave, false, true, false, ), ),
                ( Region::HighroadCave, ( 3117001, "Highroad Cave", MapName::Limgrave, false, true, false, ), ),
                ( Region::LimgraveTunnels, ( 3201001, "Limgrave Tunnels", MapName::Limgrave, false, true, false, ), ),
                ( Region::CaveofKnowledge, ( 1800090, "Cave of Knowledge", MapName::StrandedGraveyard, false, true, false, ), ),
                ( Region::StrandedGraveyard, ( 1800001, "Stranded Graveyard", MapName::StrandedGraveyard, false, true, false, ), ),
                ( Region::Stormhill, (6101000, "Stormhill", MapName::Stormhill, true, false, false), ), ( Region::MargittheFellOmen, ( 6101010, "Margit, the Fell Omen", MapName::Stormhill, false, false, true, ), ),
                ( Region::DeathtouchedCatacombs, ( 3011001, "Deathtouched Catacombs", MapName::Stormhill, false, true, false, ), ),
                ( Region::DivineTowerofLimgrave, ( 3410090, "Divine Tower of Limgrave", MapName::Stormhill, false, false, false, ), ),
                ( Region::CastleMorne, ( 6102001, "Castle Morne", MapName::WeepingPeninsula, false, false, true, ), ),
                ( Region::MorneMoangrave, ( 6102020, "Morne Moangrave", MapName::WeepingPeninsula, false, false, true, ), ),
                ( Region::WeepingPeninsulaEast, ( 6102000, "Weeping Peninsula East", MapName::WeepingPeninsula, true, false, false, ), ),
                ( Region::WeepingPeninsulaWest, ( 6102002, "Weeping Peninsula West", MapName::WeepingPeninsula, true, false, false, ), ),
                ( Region::ImpalersCatacombs, ( 3001001, "Impaler's Catacombs", MapName::WeepingPeninsula, false, true, false, ), ),
                ( Region::TombswardCatacombs, ( 3000001, "Tombsward Catacombs", MapName::WeepingPeninsula, false, true, false, ), ),
                ( Region::EarthboreCave, ( 3101001, "Earthbore Cave", MapName::WeepingPeninsula, false, true, false, ), ),
                ( Region::TombswardCave, ( 3102001, "Tombsward Cave", MapName::WeepingPeninsula, false, true, false, ), ),
                ( Region::MorneTunnel, ( 3200001, "Morne Tunnel", MapName::WeepingPeninsula, false, true, false, ), ),
                ( Region::StormveilMainGateStormveilCliffside, ( 1000001, "Stormveil Main Gate, Stormveil Cliffside", MapName::StormveilCastle, false, false, false, ), ),
                ( Region::GatesideChamber, ( 1000006, "Gateside Chamber", MapName::StormveilCastle, false, false, false, ), ),
                ( Region::RampartTower, ( 1000003, "Rampart Tower", MapName::StormveilCastle, false, false, false, ), ),
                ( Region::LiftsideChamberSecludedCell, ( 1000005, "Liftside Chamber, Secluded Cell", MapName::StormveilCastle, false, false, true, ), ),
                ( Region::GodricktheGrafted, ( 1000000, "Godrick the Grafted", MapName::StormveilCastle, false, false, true, ), ),
                ( Region::LiurniaSouthEast, ( 6200001, "Liurnia South-East", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::LiurniaEast, ( 6200004, "Liurnia East", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::BehindCariaManor, ( 6200008, "Behind Caria Manor", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::SlumberingWolfsShack, ( 3105090, "Slumbering Wolf's Shack", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::LiurniaSouth, ( 6200000, "Liurnia South", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::LiurniaSouthWest, ( 6200002, "Liurnia South-West", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::LiurniaWest, ( 6200005, "Liurnia West", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::KingsrealmRuins, ( 6200003, "Kingsrealm Ruins", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::MainCariaManorGate, ( 6200007, "Main Caria Manor Gate", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::CariaManor, ( 6200007, "Caria Manor", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::ManorLowerLevel, ( 6200007, "Manor Lower Level", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::RoyalMoongazingGrounds, ( 6200010, "Royal Moongazing Grounds", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::TheRavine, ( 6200006, "The Ravine", MapName::LiurniaOfTheLakes, true, false, false, ), ),
                ( Region::CliffbottomCatacombs, ( 3006001, "Cliffbottom Catacombs", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::RoadsEndCatacombs, ( 3003001, "Road's End Catacombs", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::BlackKnifeCatacombs, ( 3005001, "Black Knife Catacombs", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::StillwaterCave, ( 3104001, "Stillwater Cave", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::LakesideCrystalCave, ( 3105001, "Lakeside Crystal Cave", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::AcademyCrystalCave, ( 3106001, "Academy Crystal Cave", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::MainAcademyGate, ( 1400011, "Main Academy Gate", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::RayaLucariaCrystalTunnel, ( 3202001, "Raya Lucaria Crystal Tunnel", MapName::LiurniaOfTheLakes, false, true, false, ), ),
                ( Region::DivineTowerofLiurnia, ( 3411090, "Divine Tower of Liurnia", MapName::LiurniaOfTheLakes, false, false, false, ), ),
                ( Region::BellumHighway, ( 6201000, "Bellum Highway", MapName::BellumHighway, true, false, false, ), ),
                ( Region::GrandLiftofDectusJarburg, ( 6200090, "Grand Lift of Dectus, Jarburg", MapName::BellumHighway, true, false, false, ), ),
                ( Region::RuinStrewnPrecipice, ( 3920002, "Ruin-Strewn Precipice", MapName::RuinStrewnPrecipice, false, false, false, ), ),
                ( Region::RuinStrewnPrecipiceOverlook, ( 3920003, "Ruin-Strewn Precipice Overlook", MapName::RuinStrewnPrecipice, false, false, true, ), ),
                ( Region::MagmaWyrmMakar, ( 3920000, "Magma Wyrm Makar", MapName::RuinStrewnPrecipice, false, false, true, ), ),
                ( Region::MoonlightAltar, ( 6202000, "Moonlight Altar", MapName::MoonlightAltar, false, false, false, ), ),
                ( Region::ChurchoftheCuckoo, ( 1400013, "Church of the Cuckoo", MapName::AcademyOfRayaLucaria, false, false, false, ), ),
                ( Region::SchoolhouseClassroom, ( 1400015, "Schoolhouse Classroom", MapName::AcademyOfRayaLucaria, false, false, false, ), ),
                ( Region::DebateParlor, ( 1400010, "Debate Parlor", MapName::AcademyOfRayaLucaria, false, false, false, ), ),
                ( Region::RayaLucariaGrandLibrary, ( 1400000, "Raya Lucaria Grand Library", MapName::AcademyOfRayaLucaria, false, false, true, ), ),
                ( Region::RampartsidePath, ( 6300005, "Rampartside Path", MapName::AltusPlateau, true, false, false, ), ),
                ( Region::StormcallerChurchLuxRuins, ( 6300000, "Stormcaller Church, Lux Ruins", MapName::AltusPlateau, true, false, false, ), ),
                ( Region::TheShadedCastle, ( 6300001, "The Shaded Castle", MapName::AltusPlateau, false, false, false, ), ),
                ( Region::AltusHighwayJunction, ( 6300002, "Altus Highway Junction", MapName::AltusPlateau, true, false, false, ), ),
                ( Region::CastellansHall, ( 6300030, "Castellan's Hall", MapName::AltusPlateau, false, false, false, ), ),
                ( Region::ForestSpanningGreatbridge, ( 6300003, "Forest-Spanning Greatbridge", MapName::AltusPlateau, true, false, false, ), ),
                ( Region::UnsightlyCatacombs, ( 3012001, "Unsightly Catacombs", MapName::AltusPlateau, false, true, false, ), ),
                ( Region::SaintedHerosGrave, ( 3008001, "Sainted Hero's Grave", MapName::AltusPlateau, false, true, false, ), ),
                ( Region::SagesCave, ( 3119001, "Sage's Cave", MapName::AltusPlateau, false, true, false, ), ),
                ( Region::PerfumersGrotto, ( 3118001, "Perfumer's Grotto", MapName::AltusPlateau, false, true, false, ), ),
                ( Region::DominulaWindmillVillageRoadofIniquitySidePath, ( 6300004, "Dominula, Windmill Village, Road of Iniquity Side Path", MapName::AltusPlateau, true, false, false, ), ),
                ( Region::OldAltusTunnel, ( 3204001, "Old Altus Tunnel", MapName::AltusPlateau, false, true, false, ), ),
                ( Region::AltusTunnel, ( 3205001, "Altus Tunnel", MapName::AltusPlateau, false, true, false, ), ),
                ( Region::NinthMtGelmirCampsite, ( 6302000, "Ninth Mt. Gelmir Campsite", MapName::MtGelmir, true, false, false, ), ),
                ( Region::RoadofIniquity, ( 6302001, "Road of Iniquity", MapName::MtGelmir, true, false, false, ), ),
                ( Region::SeethewaterTerminusPrimevalSorcererAzur, ( 6302002, "Seethewater Terminus, Primeval Sorcerer Azur", MapName::MtGelmir, true, false, false, ), ),
                ( Region::WyndhamCatacombs, ( 3007001, "Wyndham Catacombs", MapName::MtGelmir, false, true, false, ), ),
                ( Region::GelmirHerosGrave, ( 3009001, "Gelmir Hero's Grave", MapName::MtGelmir, false, true, false, ), ),
                ( Region::SeethewaterCave, ( 3107001, "Seethewater Cave", MapName::MtGelmir, false, true, false, ), ),
                ( Region::VolcanoCave, ( 3109001, "Volcano Cave", MapName::MtGelmir, false, true, false, ), ),
                ( Region::CapitalOutskirts, ( 6301000, "Capital Outskirts", MapName::CapitalOutskirts, true, false, false, ), ),
                ( Region::CapitalRampart, ( 6301090, "Capital Rampart", MapName::CapitalOutskirts, true, false, false, ), ),
                ( Region::AurizaSideTomb, ( 3013091, "Auriza Side Tomb", MapName::CapitalOutskirts, false, true, false, ), ),
                ( Region::AurizaHerosGrave, ( 3010001, "Auriza Hero's Grave", MapName::CapitalOutskirts, false, true, false, ), ),
                ( Region::SealedTunnel, ( 3412011, "Sealed Tunnel", MapName::CapitalOutskirts, false, true, false, ), ),
                ( Region::DivineTowerofWestAltus, ( 3412090, "Divine Tower of West Altus", MapName::CapitalOutskirts, false, false, false, ), ),
                ( Region::VolcanoManor, ( 1600012, "Volcano Manor", MapName::VolcanoManor, false, false, false, ), ),
                ( Region::PrisonTownChurch, ( 1600014, "Prison Town Church", MapName::VolcanoManor, false, false, false, ), ),
                ( Region::TempleofEiglay, ( 1600010, "Temple of Eiglay", MapName::VolcanoManor, false, false, false, ), ),
                ( Region::GuestHall, ( 1600016, "Guest Hall", MapName::VolcanoManor, false, false, false, ), ),
                ( Region::AudiencePathway, ( 1600006, "Audience Pathway", MapName::VolcanoManor, false, false, true, ), ),
                ( Region::AbductorVirgin, ( 1600020, "Abductor Virgin", MapName::VolcanoManor, false, true, false, ), ),
                ( Region::SubterraneanInquisitionChamber, ( 1600022, "Subterranean Inquisition Chamber", MapName::VolcanoManor, false, false, false, ), ),
                ( Region::RykardLordofBlasphemy, ( 1600000, "Rykard, Lord of Blasphemy", MapName::VolcanoManor, false, false, true, ), ),
                ( Region::ErdtreeSanctuary, ( 1100010, "Erdtree Sanctuary", MapName::LeyndellRoyalCapital, false, false, false, ), ),
                ( Region::EastCapitalRampart, ( 1100012, "East Capital Rampart", MapName::LeyndellRoyalCapital, false, false, false, ), ),
                ( Region::LowerCapitalChurch, ( 1100015, "Lower Capital Church", MapName::LeyndellRoyalCapital, false, false, false, ), ),
                ( Region::AvenueBalcony, ( 1100013, "Avenue Balcony", MapName::LeyndellRoyalCapital, false, false, false, ), ),
                ( Region::QueensBedchamber, ( 1100001, "Queen's Bedchamber", MapName::LeyndellRoyalCapital, false, false, true, ), ),
                ( Region::WestCapitalRampartFortifiedManorFirstFloor, ( 1100016, "West Capital Rampart, Fortified Manor, First Floor", MapName::LeyndellRoyalCapital, false, false, false, ), ),
                ( Region::DivineBridge, ( 1100017, "Divine Bridge", MapName::LeyndellRoyalCapital, false, false, false, ), ),
                ( Region::EldenThrone, ( 1100000, "Elden Throne", MapName::LeyndellRoyalCapital, false, false, true, ), ),
                ( Region::UndergroundRoadside, ( 3500002, "Underground Roadside", MapName::SubterraneanShunningGrounds, false, false, false, ), ),
                ( Region::ForsakenDepths, ( 3500008, "Forsaken Depths", MapName::SubterraneanShunningGrounds, false, false, true, ), ),
                ( Region::LeyndellCatacombs, ( 3500010, "Leyndell Catacombs", MapName::SubterraneanShunningGrounds, false, false, false, ), ),
                ( Region::LeyndellCatacombsPartII, ( 3500011, "Leyndell Catacombs Part II", MapName::SubterraneanShunningGrounds, false, false, false, ), ),
                ( Region::FrenziedFlameProscription, ( 3500092, "Frenzied Flame Proscription", MapName::SubterraneanShunningGrounds, false, false, false, ), ),
                ( Region::CathedraloftheForsaken, ( 3500000, "Cathedral of the Forsaken", MapName::SubterraneanShunningGrounds, false, false, false, ), ),
                ( Region::LeyndellCapitalofAsh, ( 1105011, "Leyndell, Capital of Ash", MapName::LeyndellAshenCapital, false, false, true, ), ),
                ( Region::AshenQueensBedchamber, ( 1105001, "Queen's Bedchamber ", MapName::LeyndellAshenCapital, false, false, true, ), ),
                ( Region::AshenDivineBridge, ( 1105092, "Divine Bridge ", MapName::LeyndellAshenCapital, false, false, false, ), ),
                ( Region::AshenEldenThrone, ( 1105000, "Elden Throne ", MapName::LeyndellAshenCapital, false, false, true, ), ),
                ( Region::FracturedMarika, ( 1900000, "Fractured Marika", MapName::StonePlatform, false, false, true, ), ),
                ( Region::EldenBeast, ( 1900001, "Elden Beast", MapName::StonePlatform, false, false, true, ), ),
                ( Region::CentralCaelid, ( 6400001, "Central Caelid", MapName::Caelid, true, false, false, ), ),
                ( Region::CaelidNorth, (6400000, "Caelid North", MapName::Caelid, true, false, false), ), ( Region::ChamberOutsidethePlaza, ( 6400002, "Chamber Outside the Plaza", MapName::Caelid, false, false, true, ), ),
                ( Region::RedmaneCastlePlaza, ( 6400010, "Redmane Castle Plaza", MapName::Caelid, false, false, false, ), ),
                ( Region::StarscourgeRadahn, ( 6400040, "Starscourge Radahn", MapName::Caelid, false, false, true, ), ),
                ( Region::MinorErdtreeCatacombs, ( 3014001, "Minor Erdtree Catacombs", MapName::Caelid, false, true, false, ), ),
                ( Region::CaelidCatacombs, ( 3015001, "Caelid Catacombs", MapName::Caelid, false, true, false, ), ),
                ( Region::WarDeadCatacombs, ( 3016001, "War-Dead Catacombs", MapName::Caelid, false, true, false, ), ),
                ( Region::AbandonedCave, ( 3120001, "Abandoned Cave", MapName::Caelid, false, true, false, ), ),
                ( Region::GaolCave, (3121001, "Gaol Cave", MapName::Caelid, false, true, false), ), ( Region::GaelTunnel, (3207001, "Gael Tunnel", MapName::Caelid, false, true, false), ), 
                ( Region::GaelTunnelPartII, ( 3207002, "Gael Tunnel Part II", MapName::Caelid, false, true, false, ), ),
                ( Region::RearGaelTunnelEntrance, ( 3207090, "Rear Gael Tunnel Entrance", MapName::Caelid, false, true, false, ), ),
                ( Region::SelliaCrystalTunnel, ( 3208001, "Sellia Crystal Tunnel", MapName::Caelid, false, true, false, ), ),
                ( Region::ChairCryptofSellia, ( 6400020, "Chair-Crypt of Sellia", MapName::Caelid, true, false, false, ), ),
                ( Region::SwampofAeonia, ( 6401000, "Swamp of Aeonia", MapName::SwampOfAeonia, true, false, false, ), ),
                ( Region::Dragonbarrow, ( 6402000, "Dragonbarrow", MapName::GreyollsDragonbarrow, true, false, false, ), ),
                ( Region::SelliaHideaway, ( 3111001, "Sellia Hideaway", MapName::GreyollsDragonbarrow, true, false, false, ), ),
                ( Region::DragonbarrowCave, ( 3110001, "Dragonbarrow Cave", MapName::GreyollsDragonbarrow, true, false, false, ), ),
                ( Region::BestialSanctum, ( 6402001, "Bestial Sanctum", MapName::GreyollsDragonbarrow, true, false, false, ), ),
                ( Region::DivineTowerofCaelidCenter, ( 3413003, "Divine Tower of Caelid: Center", MapName::GreyollsDragonbarrow, false, false, false, ), ),
                ( Region::DivineTowerofCaelidBasemenr, ( 3413013, "Divine Tower of Caelid: Basement", MapName::GreyollsDragonbarrow, false, false, true, ), ),
                ( Region::IsolatedDivineTower, ( 3415090, "Isolated Divine Tower", MapName::GreyollsDragonbarrow, false, false, false, ), ),
                ( Region::ForbiddenLands, ( 6500000, "Forbidden Lands", MapName::ForbiddenLands, true, false, false, ), ),
                ( Region::GrandLiftofRold, ( 6500090, "Grand Lift of Rold", MapName::ForbiddenLands, true, false, false, ), ),
                ( Region::HiddenPathtotheHaligtree, ( 3020001, "Hidden Path to the Haligtree", MapName::ForbiddenLands, false, true, false, ), ),
                ( Region::HiddenPathtotheHaligtreePartII, ( 3020002, "Hidden Path to the Haligtree Part II", MapName::ForbiddenLands, false, true, false, ), ),
                ( Region::DivineTowerofEastAltus, ( 3414011, "Divine Tower of East Altus", MapName::ForbiddenLands, false, false, false, ), ),
                ( Region::ZamorRuins, ( 6501000, "Zamor Ruins", MapName::MountaintopsOfTheGiants, true, false, false, ), ),
                ( Region::CentralMountaintops, ( 6501001, "Central Mountaintops", MapName::MountaintopsOfTheGiants, true, false, false, ), ),
                ( Region::CastleSol, ( 6501002, "Castle Sol", MapName::MountaintopsOfTheGiants, true, false, false, ), ),
                ( Region::SpiritcallersCave, ( 3122001, "Spiritcaller's Cave", MapName::MountaintopsOfTheGiants, false, true, false, ), ),
                ( Region::CastleSolMainGateChurchoftheEclipse, ( 6501003, "Castle Sol Main Gate, Church of the Eclipse", MapName::MountaintopsOfTheGiants, true, false, false, ), ),
                ( Region::CastleSolRooftop, ( 6501010, "Castle Sol Rooftop", MapName::MountaintopsOfTheGiants, true, false, false, ), ),
                ( Region::GiantsGravepostFootoftheForge, ( 6502000, "Giants' Gravepost, Foot of the Forge", MapName::FlamePeak, false, false, true, ), ),
                ( Region::FireGiant, ( 6502010, "Fire Giant", MapName::FlamePeak, false, false, true, ), ),
                ( Region::GiantsMountaintopCatacombs, ( 3018001, "Giants' Mountaintop Catacombs", MapName::FlamePeak, false, true, false, ), ),
                ( Region::GiantConqueringHerosGrave, ( 3017002, "Giant-Conquering Hero's Grave", MapName::FlamePeak, false, true, false, ), ),
                ( Region::ConsecratedSnowfield, ( 6503000, "Consecrated Snowfield", MapName::ConsecratedSnowfield, true, false, false, ), ),
                ( Region::ConsecratedSnowfieldCatacombs, ( 3019001, "Consecrated Snowfield Catacombs", MapName::ConsecratedSnowfield, false, true, false, ), ),
                ( Region::CaveoftheForlorn, ( 3112001, "Cave of the Forlorn", MapName::ConsecratedSnowfield, false, true, false, ), ),
                ( Region::YeloughAnixTunnel, ( 3211001, "Yelough Anix Tunnel", MapName::ConsecratedSnowfield, false, true, false, ), ),
                ( Region::HaligtreeCanopy, ( 1500011, "Haligtree Canopy", MapName::MiquellasHaligtree, false, false, false, ), ),
                ( Region::HaligtreeTownPlaza, ( 1500012, "Haligtree Town Plaza", MapName::MiquellasHaligtree, false, false, true, ), ),
                ( Region::HaligtreePromenade, ( 1500010, "Haligtree Promenade", MapName::MiquellasHaligtree, false, false, true, ), ),
                ( Region::PrayerRoom, ( 1500001, "Prayer Room", MapName::ElphaelBraceOfTheHaligtree, false, false, false, ), ),
                ( Region::ElphaelInnerWallDrainageChannel, ( 1500002, "Elphael Inner Wall, Drainage Channel", MapName::ElphaelBraceOfTheHaligtree, false, false, false, ), ),
                ( Region::HaligtreeRoots, ( 1500003, "Haligtree Roots", MapName::ElphaelBraceOfTheHaligtree, false, false, true, ), ),
                ( Region::MaleniaGoddessofRot, ( 1500000, "Malenia, Goddess of Rot", MapName::ElphaelBraceOfTheHaligtree, false, false, true, ), ),
                ( Region::AinselRiverWellDepths, ( 1201001, "Ainsel River Well Depths", MapName::AinselRiver, false, false, false, ), ),
                ( Region::AinselRiverDownstream, ( 1201002, "Ainsel River Downstream", MapName::AinselRiver, false, false, false, ), ),
                ( Region::AinselRiverDownstreamPartII, ( 1201003, "Ainsel River Downstream Part II", MapName::AinselRiver, false, false, false, ), ),
                ( Region::AstelNaturalbornoftheVoid, ( 1204000, "Astel, Naturalborn of the Void", MapName::AinselRiver, false, false, true, ), ),
                ( Region::DragonkinSoldierofNokstella, ( 1201000, "Dragonkin Soldier of Nokstella", MapName::AinselRiver, false, false, false, ), ),
                ( Region::AinselRiverMain, ( 1201011, "Ainsel River Main", MapName::AinselRiverMain, false, false, false, ), ),
                ( Region::NokstellaEternalCity, ( 1201013, "Nokstella, Eternal City", MapName::AinselRiverMain, false, false, false, ), ),
                ( Region::NokstellaWaterfallBasin, ( 1201014, "Nokstella Waterfall Basin", MapName::AinselRiverMain, false, false, false, ), ),
                ( Region::LakeofRotShoreside, ( 1201015, "Lake of Rot Shoreside", MapName::LakeOfRot, false, false, false, ), ),
                ( Region::GrandCloister, ( 1201016, "Grand Cloister", MapName::LakeOfRot, false, false, false, ), ),
                ( Region::GrandCloisterPartII, ( 1201017, "Grand Cloister Part II", MapName::LakeOfRot, false, false, false, ), ),
                ( Region::NokronEternalCity, ( 1207026, "Nokron, Eternal City", MapName::NokronEternalCity, false, false, false, ), ),
                ( Region::MimicTear, ( 1202020, "Mimic Tear", MapName::NokronEternalCity, false, false, false, ), ),
                ( Region::AncestralWoods, ( 1202002, "Ancestral Woods", MapName::NokronEternalCity, false, false, false, ), ),
                ( Region::NightsSacredGround, ( 1202007, "Night's Sacred Ground", MapName::NokronEternalCity, false, false, false, ), ),
                ( Region::AqueductFacingCliffs, ( 1202003, "Aqueduct-Facing Cliffs", MapName::NokronEternalCity, false, false, false, ), ),
                ( Region::AqueductFacingCliffsPartII, ( 1202004, "Aqueduct-Facing Cliffs Part II", MapName::NokronEternalCity, false, false, true, ), ),
                ( Region::GreatWaterfallBasin, ( 1202000, "Great Waterfall Basin", MapName::NokronEternalCity, false, false, true, ), ),
                ( Region::PalaceApproachLedgeRoad, ( 1205001, "Palace Approach Ledge-Road", MapName::MohgwynPalace, false, false, false, ), ),
                ( Region::DynastyMausoleumEntrance, ( 1205004, "Dynasty Mausoleum Entrance", MapName::MohgwynPalace, false, false, false, ), ),
                ( Region::DynastyMausoleumMidpoint, ( 1205006, "Dynasty Mausoleum Midpoint", MapName::MohgwynPalace, false, false, true, ), ),
                ( Region::CocoonoftheEmpyrean, ( 1205000, "Cocoon of the Empyrean", MapName::MohgwynPalace, false, false, true, ), ),
                ( Region::SiofraRiverWellDepths, ( 1207031, "Siofra River Well Depths", MapName::SiofraRiver, false, false, false, ), ),
                ( Region::SiofraRiverBank, ( 1202033, "Siofra River Bank", MapName::SiofraRiver, false, false, false, ), ),
                ( Region::WorshippersWoods, ( 1202034, "Worshippers' Woods", MapName::SiofraRiver, false, false, false, ), ),
                ( Region::RootFacingCliffs, ( 1203001, "Root-Facing Cliffs", MapName::DeeprootDepths, false, false, false, ), ),
                ( Region::GreatWaterfallCrestPartII, ( 1203002, "Great Waterfall Crest Part II", MapName::DeeprootDepths, false, false, false, ), ),
                ( Region::DeeprootDepths, ( 1203003, "Deeproot Depths", MapName::DeeprootDepths, false, false, false, ), ),
                ( Region::TheNamelessEternalCity, ( 1203004, "The Nameless Eternal City", MapName::DeeprootDepths, false, false, false, ), ),
                ( Region::AcrosstheRoots, ( 1203005, "Across the Roots", MapName::DeeprootDepths, false, false, true, ), ),
                ( Region::PrinceofDeathsThrone, ( 1203000, "Prince of Death's Throne", MapName::DeeprootDepths, false, false, true, ), ),
                ( Region::CrumblingBeastGrave, ( 1300012, "Crumbling Beast Grave", MapName::CrumblingFarumAzula, false, false, false, ), ),
                ( Region::CrumblingBeastGraveDepthsTempestFacingBalcony, ( 1300013, "Crumbling Beast Grave Depths, Tempest-Facing Balcony", MapName::CrumblingFarumAzula, false, false, false, ), ),
                ( Region::DragonTemple, ( 1300017, "Dragon Temple", MapName::CrumblingFarumAzula, false, false, true, ), ),
                ( Region::DragonTempleTransept, ( 1300018, "Dragon Temple Transept", MapName::CrumblingFarumAzula, false, false, true, ), ),
                ( Region::DragonTempleAltar, ( 1300010, "Dragon Temple Altar", MapName::CrumblingFarumAzula, false, false, true, ), ),
                ( Region::DragonTempleLift, ( 1300019, "Dragon Temple Lift", MapName::CrumblingFarumAzula, false, false, false, ), ),
                ( Region::DragonTempleRooftop, ( 1300003, "Dragon Temple Rooftop", MapName::CrumblingFarumAzula, false, false, false, ), ),
                ( Region::DragonlordPlacidusax, ( 1300020, "Dragonlord Placidusax", MapName::CrumblingFarumAzula, false, false, true, ), ),
                ( Region::BesidetheGreatBridge, ( 1300006, "Beside the Great Bridge", MapName::CrumblingFarumAzula, false, false, true, ), ),
                ( Region::MalikeththeBlackBlade, ( 1300000, "Maliketh, the Black Blade", MapName::CrumblingFarumAzula, false, false, true, ), ),

                // DLC
                ( Region::BeluratTheatreoftheDivineBeast, (2000000, "Belurat: Theatre of the Divine Beast", MapName::RealmofShadow, false, false, true) ),
                ( Region::BeluratBeluratTowerSettlement, (2000001, "Belurat: Belurat, Tower Settlement", MapName::RealmofShadow, false, false, false) ),
                ( Region::BeluratStagefront, (2000002, "Belurat: Stagefront", MapName::RealmofShadow, false, false, false) ),
                ( Region::EnirIlimGateofDivinity, (2001000, "Enir-Ilim: Gate of Divinity", MapName::RealmofShadow, false, false, true) ),
                ( Region::EnirIlimOuterWall, (2001001, "Enir-Ilim: Outer Wall", MapName::RealmofShadow, false, false, false) ),
                ( Region::EnirIlimSpiralRise, (2001004, "Enir-Ilim: Spiral Rise", MapName::RealmofShadow, false, false, false) ),
                ( Region::EnirIlimCleansingChamberAnteroom, (2001005, "Enir-Ilim: Cleansing Chamber Anteroom", MapName::RealmofShadow, false, false, false) ),
                ( Region::EnirIlimDivineGateFrontStaircase, (2001007, "Enir-Ilim: Divine Gate Front Staircase", MapName::RealmofShadow, false, false, false) ),
                ( Region::ShadowKeepMainGate, (6900000, "Shadow Keep: Main Gate", MapName::RealmofShadow, false, false, false) ),
                ( Region::ShadowKeepMainGatePlaza, (6900010, "Shadow Keep: Main Gate Plaza", MapName::RealmofShadow, false, false, false) ),
                ( Region::ShadowKeepChurchDistrictEntrance, (2100011, "Shadow Keep: Church District Entrance", MapName::RealmofShadow, false, false, true) ),
                ( Region::ShadowKeepSunkenChapel, (2100014, "Shadow Keep: Sunken Chapel", MapName::RealmofShadow, false, false, false) ),
                ( Region::ShadowKeepTreeWorshipSanctum, (2100015, "Shadow Keep: Tree-Worship Sanctum", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseMessmersDarkChamber, (2101000, "Storehouse: Messmer's Dark Chamber", MapName::RealmofShadow, false, false, true) ),
                ( Region::StorehouseFirstFloor, (2101001, "Storehouse: First Floor", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseFourthFloor, (2101003, "Storehouse: Fourth Floor", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseSeventhFloor, (2101004, "Storehouse: Seventh Floor", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseDarkChamberEntrance, (2101006, "Storehouse: Dark Chamber Entrance", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseBackSection, (2101011, "Storehouse: Back Section", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseLoft, (2101012, "Storehouse: Loft", MapName::RealmofShadow, false, false, false) ),
                ( Region::StorehouseWestRampart, (2102001, "Storehouse: West Rampart", MapName::RealmofShadow, false, false, false) ),
                ( Region::StoneCoffinFissureGardenofDeepPurple, (2200000, "Stone Coffin Fissure: Garden of Deep Purple", MapName::RealmofShadow, false, false, true) ),
                ( Region::StoneCoffinFissureStoneCoffinFissure, (2200001, "Stone Coffin Fissure: Stone Coffin Fissure", MapName::RealmofShadow, true, false, false) ),
                ( Region::StoneCoffinFissureFissureCross, (2200002, "Stone Coffin Fissure: Fissure Cross", MapName::RealmofShadow, true, false, false) ),
                ( Region::StoneCoffinFissureFissureWaypointDepths, (2200004, "Stone Coffin Fissure: Fissure Waypoint &amp; Depths", MapName::RealmofShadow, true, false, false) ),
                ( Region::MidrasManseDiscussionChamber, (6860010, "Midra's Manse: Discussion Chamber", MapName::RealmofShadow, false, false, true) ),
                ( Region::MidrasManseManseHall, (6860001, "Midra's Manse: Manse Hall", MapName::RealmofShadow, false, false, false) ),
                ( Region::MidrasManseMidrasLibrary, (6860004, "Midra's Manse: Midra's Library", MapName::RealmofShadow, false, false, false) ),
                ( Region::GravesitePlainFogRiftCatacombs, (4000001, "Gravesite Plain: Fog Rift Catacombs", MapName::RealmofShadow, false, true, false) ),
                ( Region::GravesitePlainRuinedForgeLavaIntake, (4200090, "Gravesite Plain: Ruined Forge Lava Intake", MapName::RealmofShadow, false, true, false) ),
                ( Region::GravesitePlainRivermouthCave, (4300001, "Gravesite Plain: Rivermouth Cave", MapName::RealmofShadow, false, true, false) ),
                ( Region::GravesitePlainDragonsPit, (4200090, "Gravesite Plain: Dragon's Pit", MapName::RealmofShadow, false, true, false) ),
                ( Region::GravesitePlainDragonsPitTerminus, (4301090, "Gravesite Plain: Dragon's Pit Terminus", MapName::RealmofShadow, false, false, false) ),
                ( Region::GravesitePlainGravesitePlain, (6800000, "Gravesite Plain: Gravesite Plain", MapName::RealmofShadow, true, false, false) ),
                ( Region::GravesitePlainEllacRiverCave, (6810001, "Gravesite Plain: Ellac River Cave", MapName::RealmofShadow, true, false, false) ),
                ( Region::GravesitePlainPillarPath, (6810000, "Gravesite Plain: Pillar Path", MapName::RealmofShadow, true, false, false) ),
                ( Region::GravesitePlainBeluratGaol, (4100001, "Gravesite Plain: Belurat Gaol", MapName::RealmofShadow, false, true, false) ),
                ( Region::GravesitePlainEllacRiverDownstream, (6810090, "Gravesite Plain: Ellac River Downstream", MapName::RealmofShadow, true, false, false) ),
                ( Region::CharosHiddenGraveCharosHiddenGrave, (6840000, "Charo's Hidden Grave: Charo's Hidden Grave", MapName::RealmofShadow, true, false, false) ),
                ( Region::CharosHiddenGraveLamentersGaol, (4102001, "Charo's Hidden Grave: Lamenter's Gaol", MapName::RealmofShadow, false, true, false) ),
                ( Region::CastleEnsisCastleEnsis, (6820000, "Castle Ensis: Castle Ensis", MapName::RealmofShadow, false, false, false) ),
                ( Region::CastleEnsisEnsisMoongazingGrounds, (6820010, "Castle Ensis: Ensis Moongazing Grounds", MapName::RealmofShadow, false, false, true) ),
                ( Region::CeruleanCoastCeruleanCoast, (6830000, "Cerulean Coast: Cerulean Coast", MapName::RealmofShadow, true, false, false) ),
                ( Region::CeruleanCoastTheFissure, (6830002, "Cerulean Coast: The Fissure", MapName::RealmofShadow, true, false, false) ),
                ( Region::AbyssalWoodsAbyssalWoods, (6860000, "Abyssal Woods: Abyssal Woods", MapName::RealmofShadow, true, false, false) ),
                ( Region::AbyssalWoodsForsakenGraveyard, (4002000, "Abyssal Woods: Forsaken Graveyard", MapName::RealmofShadow, false, false, true) ),
                ( Region::FootoftheJaggedPeak, (6841000, "Foot of the Jagged Peak", MapName::RealmofShadow, true, false, false) ),
                ( Region::JaggedPeakMountainside, (6850000, "Jagged Peak: Mountainside", MapName::RealmofShadow, true, false, false) ),
                ( Region::JaggedPeakSummit, (6850001, "Jagged Peak: Summit", MapName::RealmofShadow, true, false, false) ),
                ( Region::JaggedPeakRestoftheDreadDragon, (6850010, "Jagged Peak: Rest of the Dread Dragon", MapName::RealmofShadow, false, false, true) ),
                ( Region::AncientRuinsofRauhWest, (6941000, "Ancient Ruins of Rauh: West", MapName::RealmofShadow, true, false, false) ),
                ( Region::AncientRuinsofRauhChurchoftheBud, (6941010, "Ancient Ruins of Rauh: Church of the Bud", MapName::RealmofShadow, false, false, true) ),
                ( Region::AncientRuinsofRauhEast, (6940000, "Ancient Ruins of Rauh: East", MapName::RealmofShadow, true, false, false) ),
                ( Region::RauhBaseAncientRuins, (6901000, "Rauh Base: Ancient Ruins", MapName::RealmofShadow, true, false, false) ),
                ( Region::RauhBaseScorpionRiverCatacombs, (4001001, "Rauh Base: Scorpion River Catacombs", MapName::RealmofShadow, false, true, false) ),
                ( Region::RauhBaseTaylewsRuinedForge, (4203090, "Rauh Base: Taylew's Ruined Forge", MapName::RealmofShadow, false, true, false) ),
                ( Region::ScaduAltusFingerBirthingGrounds, (2500000, "Scadu Altus: Finger Birthing Grounds", MapName::RealmofShadow, false, false, true) ),
                ( Region::ScaduAltusScaduAltus, (6900000, "Scadu Altus: Scadu Altus", MapName::RealmofShadow, true, false, false) ),
                ( Region::ScaduAltusBonnyVillage, (6902000, "Scadu Altus: Bonny Village", MapName::RealmofShadow, true, false, false) ),
                ( Region::ScaduAltusCastleWateringHole, (6903090, "Scadu Altus: Castle Watering Hole", MapName::RealmofShadow, true, false, false) ),
                ( Region::ScaduAltusReclusesRiverDownstream, (6903000, "Scadu Altus: Recluses' River Downstream", MapName::RealmofShadow, true, false, false) ),
                ( Region::ScaduAltusDarklightCatacombs, (4002001, "Scadu Altus: Darklight Catacombs", MapName::RealmofShadow, false, true, false) ),
                ( Region::ScaduAltusBonnyGaol, (4101001, "Scadu Altus: Bonny Gaol", MapName::RealmofShadow, false, true, false) ),
                ( Region::ScaduAltusRuinedForgeofStarfallPast, (4202090, "Scadu Altus: Ruined Forge of Starfall Past", MapName::RealmofShadow, false, true, false) ),
                ( Region::ScaduviewScadutreeBase, (2100010, "Scaduview: Scadutree Base", MapName::RealmofShadow, false, false, true) ),
                ( Region::ScaduviewScaduview, (2101010, "Scaduview: Scaduview", MapName::RealmofShadow, false, false, true) ),
                ( Region::ScaduviewShadowKeepBackGate, (2101013, "Scaduview: Shadow Keep, Back Gate", MapName::RealmofShadow, false, false, true) ),
                ( Region::ScaduviewHinterland, (6930000, "Scaduview: Hinterland", MapName::RealmofShadow, true, false, false) ),
            ])
        )
    }
}
